"""
store.py — PostgreSQL persistence layer for the XAU Signal bot.

The database is reached through the canonical bootstrap Postgres URL (an
asyncpg/libpq DSN,
default ``postgresql://apexvoid:apexvoid@localhost:5432/signals``). A single
lazily-created connection pool is shared across all asyncio tasks; every helper
acquires a connection for the duration of its work and releases it back.

Tables
------
pips_log
  Append-only record of every pips result the bot auto-edits in the channel
  (e.g. "+80 pips" or "-30 pips"). Queried by ``/trade_pips``
  DM command to produce win/loss summaries.

manual_signals
  Lifecycle tracker for every signal posted manually via the bot's DM interface.
  Stores the original Telegram channel message_id so the bot can later reply to
  (or reference) the exact post when the signal is closed or cancelled.

  Status flow:
    open  ──► closed     (via DM "close <id> +pips" or reply "+pips" to channel post)
        ──► cancelled  (via DM "cancel <id>" or reply "cancel" to channel post)

manual_algo_charts
  Redis OHLC windows (M1/M5/M15/H1) captured at issue, fill, and close for each
  VIP/manual signal so later formula fitting uses the same tape the owner measured.
"""

import json
import re
import time
import asyncpg
import logging
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from zoneinfo import ZoneInfo
from app.core.config import runtime_config
from app.core.symbols import pip_for
from app.autotrade.event_integrity import contradictory_archived_tp
from app.signals.pips_format import legs_achieved_pips

log = logging.getLogger(__name__)

_LEG_EPSILON = 1e-9

# Shared connection pool, created on first use so importing this module never
# opens a socket (keeps unit tests and tooling side-effect free).
_pool: asyncpg.Pool | None = None


async def _get_pool() -> asyncpg.Pool:
  global _pool
  if _pool is None:
    _pool = await asyncpg.create_pool(
      runtime_config.bootstrap.postgres.url,
      min_size=1,
      max_size=10,
      command_timeout=30,
    )
  return _pool


async def close_pool() -> None:
  """Close the shared pool. Used on shutdown and between tests."""
  global _pool
  if _pool is not None:
    await _pool.close()
    _pool = None


@asynccontextmanager
async def _connect():
  pool = await _get_pool()
  async with pool.acquire() as conn:
    yield conn


def _rowcount(status: str) -> int:
  """Parse asyncpg's command tag (e.g. ``'UPDATE 3'``) into a row count."""
  try:
    return int(status.split()[-1])
  except (ValueError, IndexError, AttributeError):
    return 0


def _current_trade_date() -> str:
  tz = ZoneInfo(runtime_config.delivery.presentation.seq_reset_tz)
  return datetime.now(tz).date().isoformat()


# ---------------------------------------------------------------------------
# Schema bootstrap
# ---------------------------------------------------------------------------

async def init_db() -> None:
  """Create all tables and indexes if they do not already exist.

  Safe to call on every application startup — every statement uses
  ``IF NOT EXISTS`` so it is a no-op when the schema is already in place.
  Call this once on startup before any other DB function.
  """
  async with _connect() as db:
    # ------------------------------------------------------------------
    # Table: pips_log
    # Appended to whenever the bot auto-edits a channel message that
    # contains a pips result (e.g. "+80 pips").  Used by /trade_pips for
    # local period summaries.
    # ------------------------------------------------------------------
    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS pips_log (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ts         BIGINT  NOT NULL,      -- unix timestamp of the edit
        sign       TEXT    NOT NULL,      -- '+' for profit, '-' for loss
        pips       INTEGER NOT NULL,      -- absolute pip count (always positive)
        message_id BIGINT,                -- Telegram message_id that was edited
        chat_id    TEXT,                  -- Telegram chat_id of the channel
        signal_id  BIGINT                 -- linked manual_signals row, if any
      )
      """
    )
    await db.execute("CREATE INDEX IF NOT EXISTS idx_pips_ts ON pips_log(ts)")
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_pips_signal_id ON pips_log(signal_id)"
    )

    # ------------------------------------------------------------------
    # Table: manual_signals
    # Tracks every signal posted to the channel via the bot's DM
    # interface ("gold sell 4100-4105 / sl 4110 / tp 95/90/80").
    # ------------------------------------------------------------------
    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS manual_signals (
        id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ts                 BIGINT           NOT NULL,
        action             TEXT             NOT NULL,
        entry              DOUBLE PRECISION NOT NULL,
        entry_end          DOUBLE PRECISION,
        sl                 DOUBLE PRECISION NOT NULL,
        original_sl        DOUBLE PRECISION,
        tps                TEXT             NOT NULL,
        order_type         TEXT             NOT NULL,
        channel_message_id BIGINT,
        status             TEXT             NOT NULL DEFAULT 'open',
        result_pips        INTEGER,
        closed_at          BIGINT,
        daily_seq          INTEGER,
        trade_date         TEXT,
        fill_state         TEXT             NOT NULL DEFAULT 'pending',
        filled_at          BIGINT,
        legs               TEXT             NOT NULL DEFAULT '[]',
        parent_id          BIGINT,
        setup_type         TEXT,
        confluence         INTEGER,
        note               TEXT,
        symbol             TEXT             NOT NULL DEFAULT 'XAU',
        visibility         TEXT             NOT NULL DEFAULT 'both',
        algo_armed         BOOLEAN          NOT NULL DEFAULT FALSE,
        trade_stream       TEXT             NOT NULL DEFAULT 'manual'
      )
      """
    )
    # Migration: original_sl records the stop as first placed and is never
    # updated (update_sl only moves `sl`). Older rows predate the column, so
    # add it idempotently and backfill from the current stop.
    await db.execute(
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS original_sl DOUBLE PRECISION"
    )
    await db.execute(
      "UPDATE manual_signals SET original_sl = sl WHERE original_sl IS NULL"
    )
    # Migration: execution lifecycle columns for the opt-in `/ algo` DM
    # suffix (manual-signal broker execution, PR 2 of 3 — infra only, no
    # broker consumes these yet). Every pre-existing row predates broker
    # execution entirely, so NULL/default is correct for all of them; there
    # is nothing to backfill, unlike original_sl above.
    await db.execute(
      # 'notify' (default, today's behavior) | 'algo' (owner armed broker
      # execution for this signal via the `/ algo` suffix).
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS execution_mode TEXT NOT NULL DEFAULT 'notify'"
    )
    await db.execute(
      # NULL (never armed) | 'armed' | 'filled' | 'closed' | 'cancelled' |
      # 'rejected' | 'error'.
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS execution_status TEXT"
    )
    await db.execute(
      # Stable id of the published ManualTradeIntent, 'manual:<id>:<revision>'.
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS execution_intent_id TEXT"
    )
    await db.execute(
      # Bumped each time a new intent is published for the same signal
      # (e.g. a re-arm after SL/TP edit) — not used anywhere yet in this PR.
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS execution_revision INTEGER NOT NULL DEFAULT 0"
    )
    await db.execute(
      # Broker-side position id once filled. Internal only — never rendered
      # to Telegram.
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS broker_position_id TEXT"
    )
    await db.execute(
      # Actual broker fill price, once filled.
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS broker_fill_price DOUBLE PRECISION"
    )
    await db.execute(
      # Last error message from an arm/fill/close attempt, if any.
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS execution_error TEXT"
    )
    await db.execute(
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS algo_armed BOOLEAN NOT NULL DEFAULT FALSE"
    )
    await db.execute(
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS trade_stream TEXT NOT NULL DEFAULT 'manual'"
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_manual_signals_execution_intent_id "
      "ON manual_signals(execution_intent_id)"
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_manual_signals_status "
      "ON manual_signals(status)"
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_manual_signals_trade_date "
      "ON manual_signals(trade_date)"
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_manual_signals_symbol_trade_date "
      "ON manual_signals(symbol, trade_date)"
    )
    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS manual_algo_charts (
        id            BIGSERIAL PRIMARY KEY,
        signal_id     BIGINT NOT NULL REFERENCES manual_signals(id),
        event         TEXT   NOT NULL,
        captured_at   BIGINT NOT NULL,
        symbol        TEXT   NOT NULL,
        timeframe     TEXT   NOT NULL,
        window_start  BIGINT NOT NULL,
        window_end    BIGINT NOT NULL,
        bars          JSONB  NOT NULL,
        UNIQUE (signal_id, event, timeframe)
      )
      """
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_manual_algo_charts_signal "
      "ON manual_algo_charts(signal_id, event)"
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_manual_signals_parent_id "
      "ON manual_signals(parent_id)"
    )

    # Broker execution ledger. Fills and results are separate so scale-ins
    # retain their real fill count while one group result remains one trade.
    # correction_source is also a durable replay fence: a narrowly audited
    # historical correction must not be reverted by the generic Redis
    # backfill replaying the original malformed terminal events.
    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS auto_trade_fills (
        position_id BIGINT PRIMARY KEY,
        group_id    TEXT             NOT NULL,
        trade_key   TEXT             NOT NULL,
        trade_stream TEXT            NOT NULL,
        symbol      TEXT             NOT NULL DEFAULT 'XAU',
        setup_type  TEXT,
        direction   TEXT,
        entry_price DOUBLE PRECISION,
        stop_pips   DOUBLE PRECISION,
        volume      BIGINT,
        filled_at   BIGINT           NOT NULL,
        correction_source TEXT,
        corrected_at BIGINT
      )
      """
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_auto_trade_fills_group "
      "ON auto_trade_fills(group_id)"
    )
    for stmt in (
      "ALTER TABLE auto_trade_fills "
      "ADD COLUMN IF NOT EXISTS correction_source TEXT",
      "ALTER TABLE auto_trade_fills "
      "ADD COLUMN IF NOT EXISTS corrected_at BIGINT",
    ):
      await db.execute(stmt)
    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS auto_trade_results (
        group_id     TEXT PRIMARY KEY,
        trade_key    TEXT             NOT NULL,
        trade_stream TEXT             NOT NULL,
        result_pips  DOUBLE PRECISION NOT NULL,
        closed_at    BIGINT           NOT NULL
      )
      """
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_auto_trade_results_closed "
      "ON auto_trade_results(closed_at)"
    )
    for stmt in (
      "ALTER TABLE auto_trade_results ADD COLUMN IF NOT EXISTS setup_type TEXT",
      "ALTER TABLE auto_trade_results ADD COLUMN IF NOT EXISTS direction TEXT",
      "ALTER TABLE auto_trade_results ADD COLUMN IF NOT EXISTS session TEXT",
      "ALTER TABLE auto_trade_results ADD COLUMN IF NOT EXISTS killzone_name TEXT",
      "ALTER TABLE auto_trade_results ADD COLUMN IF NOT EXISTS stop_pips DOUBLE PRECISION",
      "ALTER TABLE auto_trade_results ADD COLUMN IF NOT EXISTS booked_tp_count INTEGER",
      "ALTER TABLE auto_trade_results ADD COLUMN IF NOT EXISTS utc_hour INTEGER",
      "ALTER TABLE auto_trade_results ADD COLUMN IF NOT EXISTS symbol TEXT NOT NULL DEFAULT 'XAU'",
      "ALTER TABLE auto_trade_results ADD COLUMN IF NOT EXISTS correction_source TEXT",
      "ALTER TABLE auto_trade_results ADD COLUMN IF NOT EXISTS corrected_at BIGINT",
    ):
      await db.execute(stmt)

    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS signal_posts (
        signal_id  BIGINT NOT NULL,
        channel_id BIGINT NOT NULL,
        message_id BIGINT NOT NULL,
        tier       TEXT   NOT NULL,
        PRIMARY KEY (signal_id, channel_id)
      )
      """
    )
    await db.execute(
      "CREATE UNIQUE INDEX IF NOT EXISTS idx_signal_posts_message "
      "ON signal_posts(channel_id, message_id)"
    )
    # Back-fill VIP posts for signals stored before signal_posts existed.
    await db.execute(
      """
      INSERT INTO signal_posts (signal_id, channel_id, message_id, tier)
      SELECT id, $1, channel_message_id, 'vip'
      FROM manual_signals
      WHERE channel_message_id IS NOT NULL
      -- Unqualified DO NOTHING mirrors SQLite's INSERT OR IGNORE: skip a row
      -- that collides on *either* unique constraint (PK or message_id).
      ON CONFLICT DO NOTHING
      """,
      runtime_config.delivery.telegram.telegram_channel_id,
    )

    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS events (
        event_id  TEXT    PRIMARY KEY,
        ts_utc    BIGINT  NOT NULL,
        currency  TEXT    NOT NULL,
        title     TEXT    NOT NULL,
        impact    TEXT    NOT NULL,
        forecast  TEXT,
        previous  TEXT,
        actual    TEXT,
        all_day   INTEGER NOT NULL DEFAULT 0,
        source    TEXT    NOT NULL DEFAULT 'ff',
        synced_at BIGINT  NOT NULL
      )
      """
    )
    await db.execute("CREATE INDEX IF NOT EXISTS idx_events_ts ON events(ts_utc)")
    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS meta (
        key   TEXT PRIMARY KEY,
        value TEXT
      )
      """
    )


# ---------------------------------------------------------------------------
# Economic calendar
# ---------------------------------------------------------------------------

async def upsert_events(rows: list[dict]) -> None:
  """Insert calendar events, refreshing release values on repeat syncs."""
  if not rows:
    return
  values = [
    (
      row["event_id"], row["ts_utc"], row["currency"], row["title"],
      row["impact"], row.get("forecast"), row.get("previous"),
      row.get("actual"), row.get("all_day", 0),
      row.get("source", "ff"), row["synced_at"],
    )
    for row in rows
  ]
  async with _connect() as db:
    await db.executemany(
      """
      INSERT INTO events (
        event_id, ts_utc, currency, title, impact, forecast, previous,
        actual, all_day, source, synced_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
      ON CONFLICT (event_id) DO UPDATE SET
        forecast = excluded.forecast,
        previous = excluded.previous,
        actual = COALESCE(excluded.actual, events.actual),
        synced_at = excluded.synced_at
      """,
      values,
    )


async def events_between(start_utc: int, end_utc: int) -> list[dict]:
  """Return stored high-impact events in chronological order."""
  async with _connect() as db:
    rows = await db.fetch(
      """
      SELECT * FROM events
      WHERE impact = 'High' AND ts_utc >= $1 AND ts_utc < $2
      ORDER BY ts_utc ASC, title ASC
      """,
      start_utc, end_utc,
    )
  return [dict(row) for row in rows]


async def event_in_window(now: int, horizon: int) -> dict | None:
  """Return the nearest timed event from 30m ago through the horizon."""
  async with _connect() as db:
    row = await db.fetchrow(
      """
      SELECT * FROM events
      WHERE impact = 'High'
        AND all_day = 0
        AND ts_utc >= $1
        AND ts_utc <= $2
      ORDER BY ABS(ts_utc - $3) ASC, ts_utc ASC
      LIMIT 1
      """,
      now - 1800, now + horizon, now,
    )
  return dict(row) if row else None


async def nearest_currency_event(
  currency: str, start_utc: int, end_utc: int, anchor: int,
) -> dict | None:
  """Nearest-to-anchor high-impact timed event for one currency in a span."""
  async with _connect() as db:
    row = await db.fetchrow(
      """
      SELECT * FROM events
      WHERE impact = 'High'
        AND all_day = 0
        AND currency = $1
        AND ts_utc >= $2
        AND ts_utc <= $3
      ORDER BY ABS(ts_utc - $4) ASC, ts_utc ASC
      LIMIT 1
      """,
      currency.upper(), start_utc, end_utc, anchor,
    )
  return dict(row) if row else None


async def get_meta(key: str) -> str | None:
  async with _connect() as db:
    return await db.fetchval("SELECT value FROM meta WHERE key = $1", key)


async def set_meta(key: str, value: str) -> None:
  async with _connect() as db:
    await db.execute(
      """
      INSERT INTO meta (key, value) VALUES ($1, $2)
      ON CONFLICT (key) DO UPDATE SET value = excluded.value
      """,
      key, value,
    )


# ---------------------------------------------------------------------------
# pips_log helpers
# ---------------------------------------------------------------------------

async def store_pips(
  sign: str,
  pips: int,
  message_id: int = None,
  chat_id: str = None,
  signal_id: int = None,
) -> None:
  """Append one pips result to the log.

  Args:
    sign:       ``'+'`` for a winning trade, ``'-'`` for a loss.
    pips:       Absolute pip count (always positive; sign carries direction).
    message_id: Telegram message_id of the edited channel post (optional).
    chat_id:    Telegram chat_id of the channel (optional).
    signal_id:  Linked manual signal primary key (optional).
  """
  async with _connect() as db:
    await db.execute(
      "INSERT INTO pips_log "
      "(ts, sign, pips, message_id, chat_id, signal_id) "
      "VALUES ($1, $2, $3, $4, $5, $6)",
      int(time.time()), sign, pips, message_id,
      str(chat_id) if chat_id else None, signal_id,
    )


async def get_pips_summary(
  start_ts: int,
  end_ts: int,
  symbol: str | None = None,
) -> dict:
  """Aggregate pips results within a Unix timestamp range.

  Returns:
    A dict with keys:
      wins       — number of winning trades in the period.
      win_pips   — total pips gained from winners.
      losses     — number of losing trades in the period.
      loss_pips  — total pips lost from losers (positive integer).
      net        — net pips (win_pips - loss_pips); negative means net loss.
      total      — total number of trades recorded (wins + losses).
  """
  query = (
    "SELECT p.sign, p.pips FROM pips_log p "
    "LEFT JOIN manual_signals s ON s.id = p.signal_id "
    "WHERE p.ts >= $1 AND p.ts <= $2"
  )
  params: list = [start_ts, end_ts]
  if symbol:
    query += " AND s.symbol = $3"
    params.append(symbol.upper())
  async with _connect() as db:
    records = await db.fetch(query, *params)
  rows = [(r["sign"], r["pips"]) for r in records]
  wins   = [(s, p) for s, p in rows if s == '+']
  losses = [(s, p) for s, p in rows if s == '-']
  net    = sum(p if s == '+' else -p for s, p in rows)
  return {
    'wins': len(wins), 'win_pips': sum(p for _, p in wins),
    'losses': len(losses), 'loss_pips': sum(p for _, p in losses),
    'net': net, 'total': len(rows),
  }


async def get_pips_records(
  start_ts: int,
  end_ts: int,
  symbol: str | None = None,
) -> list[dict]:
  """Return manual and broker execution results, oldest first."""
  query = """
    SELECT p.id, p.ts, p.sign, p.pips, p.signal_id,
           s.ts AS signal_ts, s.action, s.entry, s.entry_end,
           s.parent_id, s.setup_type, s.daily_seq, s.symbol,
           s.original_sl, 'manual'::TEXT AS stream,
           ('manual:' || COALESCE(p.signal_id::TEXT, 'pips:' || p.id::TEXT))
             AS trade_key,
           1::BIGINT AS fill_count
    FROM pips_log p
    LEFT JOIN manual_signals s ON s.id = p.signal_id
    WHERE p.ts >= $1 AND p.ts <= $2
  """
  params: list = [start_ts, end_ts]
  if symbol:
    query += " AND s.symbol = $3"
    params.append(symbol.upper())
  query += " ORDER BY p.ts ASC, p.id ASC"
  async with _connect() as db:
    manual_rows = await db.fetch(query, *params)
    algo_query = """
      SELECT r.group_id AS id, r.closed_at AS ts,
             CASE WHEN r.result_pips >= 0 THEN '+' ELSE '-' END AS sign,
             ABS(ROUND(r.result_pips))::INTEGER AS pips,
             NULL::BIGINT AS signal_id,
             MIN(f.filled_at) AS signal_ts,
             MIN(f.direction) AS action,
             AVG(f.entry_price) AS entry,
             AVG(f.entry_price) AS entry_end,
             NULL::BIGINT AS parent_id,
             MIN(f.setup_type) AS setup_type,
             NULL::INTEGER AS daily_seq,
             MIN(f.symbol) AS symbol,
             NULL::DOUBLE PRECISION AS original_sl,
             r.trade_stream AS stream,
             r.trade_key,
             COUNT(*)::BIGINT AS fill_count,
             AVG(f.stop_pips) AS stop_pips,
             r.result_pips / NULLIF(AVG(f.stop_pips), 0) AS r_multiple
      FROM auto_trade_results r
      JOIN auto_trade_fills f ON f.group_id = r.group_id
      WHERE r.closed_at >= $1 AND r.closed_at <= $2
    """
    algo_params: list = [start_ts, end_ts]
    if symbol:
      algo_query += " AND f.symbol = $3"
      algo_params.append(symbol.upper())
    algo_query += (
      " GROUP BY r.group_id, r.closed_at, r.result_pips, "
      "r.trade_stream, r.trade_key ORDER BY r.closed_at ASC, r.group_id ASC"
    )
    algo_rows = await db.fetch(algo_query, *algo_params)

  records = [dict(row) for row in manual_rows]
  for record in records:
    signal_symbol = record.get("symbol") or "XAU"
    entry = record.get("entry")
    entry_end = record.get("entry_end")
    stop = record.get("original_sl")
    if entry is None or stop is None:
      continue
    reference = (
      entry_end if record.get("action") == "BUY" and entry_end is not None
      else entry
    )
    stop_pips = abs(float(reference) - float(stop)) / pip_for(signal_symbol)
    record["stop_pips"] = stop_pips
    record["r_multiple"] = (
      (record["pips"] if record["sign"] == "+" else -record["pips"])
      / stop_pips
      if stop_pips > 0 else None
    )
  records.extend(dict(row) for row in algo_rows)
  return sorted(records, key=lambda row: (row["ts"], str(row["id"])))


async def record_auto_trade_event(event: dict) -> None:
  """Persist fill attribution and terminal broker results idempotently."""
  event_type = str(event.get("type") or "")
  if event_type in {"opened", "add", "manual_opened", "order_filled"}:
    await _record_auto_trade_fill(event)
  elif event_type in {"group_result", "position_closed", "manual_closed"}:
    await _record_auto_trade_result(event)


def _resolve_auto_trade_stream(event: dict) -> str:
  stream = str(event.get("stream") or "").strip()
  if stream in {"algo_auto", "algo_manual"}:
    return stream
  # TradePlan events omit stream; attribute them as autonomous algo.
  candidate = str(event.get("candidate_id") or "")
  group_id = str(event.get("group_id") or "")
  if candidate.startswith("v8:") or group_id.startswith("v8:"):
    return "algo_auto"
  setup = str(event.get("setup") or "").strip().lower()
  if setup == "manual algo":
    return "algo_manual"
  if event.get("position_id") is not None and (
    event.get("setup") or event.get("direction")
  ):
    return "algo_auto"
  return stream


def _resolve_fill_stop_pips(event: dict, symbol: str) -> float | None:
  raw = event.get("stop_pips")
  if raw is not None:
    try:
      value = float(raw)
    except (TypeError, ValueError):
      value = None
    else:
      if value > 0:
        return value
  stop_loss = event.get("stop_loss")
  entry = event.get("price")
  if stop_loss is None or entry is None:
    return None
  try:
    return abs(float(entry) - float(stop_loss)) / pip_for(symbol)
  except (TypeError, ValueError, ZeroDivisionError):
    return None


async def _record_auto_trade_fill(event: dict) -> None:
  position_id = event.get("position_id")
  stream = _resolve_auto_trade_stream(event)
  if position_id is None or stream not in {"algo_auto", "algo_manual"}:
    return
  group_id = str(event.get("group_id") or position_id)
  trade_key = f"algo:{group_id}"
  candidate_id = str(event.get("candidate_id") or "")
  symbol = str(event.get("symbol") or "XAU").upper()
  stop_pips = _resolve_fill_stop_pips(event, symbol)
  from app.autotrade.reaction_funnel import normalize_setup_type

  setup_type = normalize_setup_type(
    event.get("setup") or event.get("setup_type") or event.get("strategy"),
  )
  async with _connect() as db:
    if stream == "algo_manual" and candidate_id:
      signal_id = await db.fetchval(
        "SELECT id FROM manual_signals "
        "WHERE execution_intent_id LIKE $1 || '%' "
        "ORDER BY id DESC LIMIT 1",
        candidate_id[:10],
      )
      if signal_id is not None:
        trade_key = f"manual:{signal_id}"
        await db.execute(
          "UPDATE manual_signals SET trade_stream = 'algo_manual' "
          "WHERE id = $1",
          signal_id,
        )
    await db.execute(
      """
      INSERT INTO auto_trade_fills (
        position_id, group_id, trade_key, trade_stream, symbol,
        setup_type, direction, entry_price, stop_pips, volume, filled_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
      ON CONFLICT (position_id) DO UPDATE SET
        group_id = excluded.group_id,
        trade_key = excluded.trade_key,
        trade_stream = excluded.trade_stream,
        symbol = excluded.symbol,
        setup_type = COALESCE(excluded.setup_type, auto_trade_fills.setup_type),
        direction = COALESCE(excluded.direction, auto_trade_fills.direction),
        entry_price = COALESCE(excluded.entry_price, auto_trade_fills.entry_price),
        stop_pips = COALESCE(excluded.stop_pips, auto_trade_fills.stop_pips),
        volume = COALESCE(excluded.volume, auto_trade_fills.volume)
      WHERE auto_trade_fills.correction_source IS NULL
      """,
      int(position_id), group_id, trade_key, stream,
      symbol, setup_type,
      event.get("direction"), event.get("price"), stop_pips,
      event.get("volume"), int(event.get("timestamp") or time.time()),
    )


async def _record_auto_trade_result(event: dict) -> None:
  if (
    event.get("type") == "manual_closed"
    and (
      event.get("remaining_volume") is None
      or int(event["remaining_volume"]) > 0
    )
  ):
    return
  group_id = str(event.get("group_id") or "").strip()
  position_id = event.get("position_id")
  async with _connect() as db:
    if not group_id and position_id is not None:
      group_id = str(await db.fetchval(
        "SELECT group_id FROM auto_trade_fills WHERE position_id = $1",
        int(position_id),
      ) or "")
    if not group_id:
      return
    fill = await db.fetchrow(
      "SELECT trade_key, trade_stream, setup_type, direction, stop_pips, symbol "
      "FROM auto_trade_fills "
      "WHERE group_id = $1 ORDER BY filled_at ASC LIMIT 1",
      group_id,
    )
    if fill is None:
      return
    if (
      event.get("type") == "position_closed"
      and await db.fetchval(
        "SELECT 1 FROM auto_trade_results WHERE group_id = $1", group_id,
      )
    ):
      return
    message = str(event.get("message") or "")
    message_cf = message.casefold()
    contradictory_tp = contradictory_archived_tp(event, message)
    no_tp_archived = "no tp archived" in message_cf or contradictory_tp
    highest_tp_archived = (
      "highest tp archived" in message_cf and not contradictory_tp
    )
    result_pips = None
    if highest_tp_archived and event.get("target_pips") is not None:
      # Owner directive: /trade_stats records the highest TP actually
      # archived across the whole system, not a volume-weighted blended
      # net - same convention as legs_achieved_pips in manual_signals.
      # This must win over group_realized_pips (the real broker blend)
      # whenever a TP was archived, not just fill the gap when it's absent.
      try:
        archived_pips = float(event["target_pips"])
      except (TypeError, ValueError):
        archived_pips = None
      if archived_pips is not None:
        result_pips = abs(archived_pips)
    if result_pips is None:
      result_pips = event.get("group_realized_pips")
    if result_pips is None and no_tp_archived:
      # Loss path only: SL with zero TPs booked. Never invent a loss from a
      # residual BE/SL exit after a booked TP.
      losing_match = re.search(
        r"losing\s+(-?\d+(?:\.\d+)?)\s*pips?",
        message_cf,
      )
      if losing_match is not None:
        try:
          result_pips = float(losing_match.group(1))
        except (TypeError, ValueError):
          result_pips = None
    if result_pips is None:
      winning_match = re.search(
        r"winning\s+(-?\d+(?:\.\d+)?)\s*pips?",
        message_cf,
      )
      if winning_match is not None:
        try:
          result_pips = float(winning_match.group(1))
        except (TypeError, ValueError):
          result_pips = None
    if result_pips is None and event.get("type") in {
      "position_closed", "manual_closed",
    }:
      fills = await db.fetch(
        "SELECT symbol, direction, entry_price, volume, stop_pips "
        "FROM auto_trade_fills WHERE group_id = $1",
        group_id,
      )
      exit_price = event.get("price")
      if exit_price is not None:
        # Highest signed move from any fill entry to the exit — never a
        # volume-weighted lot net, which dilutes booked TPs with BE residual.
        peak = None
        for row in fills:
          if row["entry_price"] is None:
            continue
          move = float(exit_price) - float(row["entry_price"])
          if str(row["direction"]).upper() == "SELL":
            move = -move
          pips = move / pip_for(row["symbol"] or "XAU")
          peak = pips if peak is None else max(peak, pips)
        if peak is not None:
          if highest_tp_archived:
            # Booked TP already happened — residual exit must not flip this
            # into a loss. Keep positive/zero peak only as a last resort.
            if peak >= 0:
              result_pips = peak
          elif no_tp_archived or not highest_tp_archived:
            result_pips = peak
      if result_pips is None and no_tp_archived:
        # Full SL, no broker exit price: approximate from planned stop.
        stops = [
          float(row["stop_pips"])
          for row in fills
          if row["stop_pips"] is not None and float(row["stop_pips"]) > 0
        ]
        if stops:
          result_pips = -sum(stops) / len(stops)
    if result_pips is None:
      return
    # Loss only for SL with no TP archived. A residual BE/SL after a booked
    # TP must never flip the trade into a loser in /trade_stats.
    if float(result_pips) < 0 and highest_tp_archived:
      if event.get("target_pips") is not None:
        try:
          result_pips = abs(float(event["target_pips"]))
        except (TypeError, ValueError):
          return
      else:
        return
    closed_at = int(event.get("timestamp") or time.time())
    utc_hour = datetime.fromtimestamp(closed_at, tz=timezone.utc).hour
    if 7 <= utc_hour < 13:
      session = "london"
    elif 13 <= utc_hour < 21:
      session = "new_york"
    else:
      session = "asia"
    try:
      from app.autotrade.killzone import classify_killzone
      kz_name = classify_killzone(ts=closed_at).killzone_name
    except Exception:
      kz_name = None
    booked_tp_count = None
    if highest_tp_archived:
      booked_tp_count = 1
      for token, count in (("tp5", 5), ("tp4", 4), ("tp3", 3), ("tp2", 2), ("tp1", 1)):
        if token in message_cf:
          booked_tp_count = count
          break
      try:
        if event.get("target_index") is not None:
          booked_tp_count = max(booked_tp_count, int(event["target_index"]))
      except (TypeError, ValueError):
        pass
    elif no_tp_archived:
      booked_tp_count = 0
    await db.execute(
      """
      INSERT INTO auto_trade_results (
        group_id, trade_key, trade_stream, result_pips, closed_at,
        setup_type, direction, session, killzone_name, stop_pips,
        booked_tp_count, utc_hour, symbol
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
      ON CONFLICT (group_id) DO UPDATE SET
        trade_key = excluded.trade_key,
        trade_stream = excluded.trade_stream,
        result_pips = excluded.result_pips,
        closed_at = excluded.closed_at,
        setup_type = COALESCE(excluded.setup_type, auto_trade_results.setup_type),
        direction = COALESCE(excluded.direction, auto_trade_results.direction),
        session = COALESCE(excluded.session, auto_trade_results.session),
        killzone_name = COALESCE(excluded.killzone_name, auto_trade_results.killzone_name),
        stop_pips = COALESCE(excluded.stop_pips, auto_trade_results.stop_pips),
        booked_tp_count = COALESCE(excluded.booked_tp_count, auto_trade_results.booked_tp_count),
        utc_hour = COALESCE(excluded.utc_hour, auto_trade_results.utc_hour),
        symbol = COALESCE(excluded.symbol, auto_trade_results.symbol)
      WHERE auto_trade_results.correction_source IS NULL
      """,
      group_id, fill["trade_key"], fill["trade_stream"],
      float(result_pips), closed_at,
      fill["setup_type"], fill["direction"], session, kz_name,
      fill["stop_pips"], booked_tp_count, utc_hour,
      fill["symbol"] or "XAU",
    )


# ---------------------------------------------------------------------------
# Manual signal lifecycle
# ---------------------------------------------------------------------------

async def store_manual_signal(
  ts: int,
  action: str,
  entry: float,
  entry_end: float,
  sl: float,
  tps: list[float],
  channel_message_id: int | None = None,
  parent_id: int | None = None,
  setup_type: str | None = None,
  confluence: int | None = None,
  symbol: str = "XAU",
  visibility: str = "both",
  execution_mode: str = "notify",
) -> dict:
  """Insert a manual signal and return its primary and daily display ids.

  Args:
    execution_mode: ``'notify'`` (default) posts to the channel only, as
      today. ``'algo'`` additionally arms broker-side execution (handled by
      the caller — this function only persists the flag, it does not branch
      on it).

  Returns:
    A dict containing the primary key ``id`` and today's ``daily_seq``.
  """
  symbol = symbol.upper()
  visibility = visibility.lower()
  if visibility not in {"both", "vip"}:
    raise ValueError(f"Invalid visibility: {visibility}")
  trade_date = _current_trade_date()
  async with _connect() as db:
    async with db.transaction():
      # Serialize concurrent inserts scoped to (symbol, trade_date) so the
      # daily_seq numbering stays gapless, mirroring the old BEGIN IMMEDIATE.
      await db.execute(
        "SELECT pg_advisory_xact_lock(hashtextextended($1, 0))",
        f"{symbol}:{trade_date}",
      )
      count = await db.fetchval(
        "SELECT COUNT(*) FROM manual_signals "
        "WHERE symbol = $1 AND trade_date = $2",
        symbol, trade_date,
      )
      daily_seq = count + 1
      new_id = await db.fetchval(
        """
        INSERT INTO manual_signals
          (ts, action, entry, entry_end, sl, original_sl, tps, order_type,
           channel_message_id, daily_seq, trade_date, parent_id,
           setup_type, confluence, symbol, visibility, execution_mode)
        VALUES ($1, $2, $3, $4, $5, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
        RETURNING id
        """,
        ts, action, entry, entry_end, sl, json.dumps(tps), "zone",
        channel_message_id, daily_seq, trade_date, parent_id,
        setup_type, confluence, symbol, visibility, execution_mode,
      )
  await _safe_snapshot_manual_chart(
    signal_id=int(new_id),
    event="issued",
    ts=int(ts),
    symbol=symbol,
  )
  return {
    "id": new_id,
    "daily_seq": daily_seq,
    "symbol": symbol,
    "visibility": visibility,
  }


async def set_manual_signal_channel_id(row_id: int, channel_message_id: int) -> None:
  """Back-fill the channel_message_id for an already-inserted manual signal."""
  async with _connect() as db:
    async with db.transaction():
      await db.execute(
        "UPDATE manual_signals SET channel_message_id = $1 WHERE id = $2",
        channel_message_id, row_id,
      )
      await db.execute(
        """
        INSERT INTO signal_posts (signal_id, channel_id, message_id, tier)
        VALUES ($1, $2, $3, 'vip')
        ON CONFLICT (signal_id, channel_id) DO UPDATE SET
          message_id = excluded.message_id,
          tier = 'vip'
        """,
        row_id, runtime_config.delivery.telegram.telegram_channel_id, channel_message_id,
      )


async def insert_signal_post(
  signal_id: int,
  channel_id: int,
  message_id: int,
  tier: str,
) -> None:
  """Record one delivered signal post and retain the VIP compatibility id."""
  async with _connect() as db:
    async with db.transaction():
      await db.execute(
        """
        INSERT INTO signal_posts (signal_id, channel_id, message_id, tier)
        VALUES ($1, $2, $3, $4)
        ON CONFLICT (signal_id, channel_id) DO UPDATE SET
          message_id = excluded.message_id,
          tier = excluded.tier
        """,
        signal_id, int(channel_id), message_id, tier,
      )
      if tier == "vip":
        await db.execute(
          "UPDATE manual_signals SET channel_message_id = $1 WHERE id = $2",
          message_id, signal_id,
        )


async def get_signal_posts(signal_id: int) -> list[dict]:
  async with _connect() as db:
    rows = await db.fetch(
      "SELECT * FROM signal_posts WHERE signal_id = $1 "
      "ORDER BY CASE tier WHEN 'vip' THEN 0 ELSE 1 END, channel_id",
      signal_id,
    )
  return [dict(row) for row in rows]


async def get_signal_by_post(
  channel_id: int,
  message_id: int,
  *,
  open_only: bool = False,
) -> dict | None:
  if open_only:
    await expire_unfilled_pending_signals()
  query = (
    "SELECT s.* FROM signal_posts p "
    "JOIN manual_signals s ON s.id = p.signal_id "
    "WHERE p.channel_id = $1 AND p.message_id = $2"
  )
  if open_only:
    query += " AND s.status = 'open'"
  async with _connect() as db:
    row = await db.fetchrow(query, int(channel_id), message_id)
  return _decode_signal(row) if row else None


async def get_open_signals(symbol: str | None = None) -> list[dict]:
  """Return all signals currently in ``status = 'open'``, oldest first."""
  await expire_unfilled_pending_signals()
  query = (
    "SELECT id, ts, action, entry, entry_end, sl, tps, "
    "channel_message_id, daily_seq, trade_date, fill_state, filled_at, legs, "
    "parent_id, setup_type, confluence, note, status, result_pips, "
    "symbol, visibility, algo_armed "
    "FROM manual_signals WHERE status = 'open'"
  )
  params: list = []
  if symbol:
    query += " AND symbol = $1"
    params.append(symbol.upper())
  query += " ORDER BY ts ASC"
  async with _connect() as db:
    rows = await db.fetch(query, *params)
  return [_decode_signal(r) for r in rows]


async def expire_unfilled_pending_signals() -> list[dict]:
  """Cancel pending open signals that did not fill on their trade date."""
  today = _current_trade_date()
  now = int(time.time())
  async with _connect() as db:
    rows = await db.fetch(
      """
      UPDATE manual_signals
      SET status = 'cancelled', closed_at = $1, algo_armed = FALSE
      WHERE status = 'open'
        AND fill_state = 'pending'
        AND (trade_date IS NULL OR trade_date < $2)
      RETURNING *
      """,
      now, today,
    )
  if rows:
    log.info("Auto-cancelled %s stale pending signal(s)", len(rows))
  return [_decode_signal(row) for row in rows]


async def count_pending_algo_signals() -> int:
  """Manual /algo orders still resting at the broker, not yet resolved."""
  async with _connect() as db:
    return int(await db.fetchval(
      "SELECT COUNT(*) FROM manual_signals "
      "WHERE execution_mode = 'algo' AND status = 'open' "
      "AND execution_status = 'pending'",
    ))


def _decode_signal(row) -> dict:
  """Convert one signal row to a dict and deserialize its JSON fields."""
  result = dict(row)
  result["tps"] = json.loads(result.get("tps") or "[]")
  result["legs"] = json.loads(result.get("legs") or "[]")
  return result


async def get_all_signals(symbol: str | None = None) -> list[dict]:
  """Return every manual signal, oldest first."""
  query = "SELECT * FROM manual_signals"
  params: list = []
  if symbol:
    query += " WHERE symbol = $1"
    params.append(symbol.upper())
  query += " ORDER BY ts ASC, id ASC"
  async with _connect() as db:
    rows = await db.fetch(query, *params)
  return [_decode_signal(row) for row in rows]


async def get_untagged_signals(limit: int = 20) -> list[dict]:
  """Return recent signals whose setup metadata still needs backfilling."""
  limit = max(1, min(100, int(limit)))
  async with _connect() as db:
    rows = await db.fetch(
      "SELECT * FROM manual_signals "
      "WHERE setup_type IS NULL "
      "ORDER BY ts DESC, id DESC LIMIT $1",
      limit,
    )
  return [_decode_signal(row) for row in rows]


async def upsert_manual_algo_chart(
  *,
  signal_id: int,
  event: str,
  captured_at: int,
  symbol: str,
  timeframe: str,
  window_start: int,
  window_end: int,
  bars: list,
) -> None:
  """Idempotent OHLC snapshot for one signal event and timeframe."""
  async with _connect() as db:
    await db.execute(
      """
      INSERT INTO manual_algo_charts
        (signal_id, event, captured_at, symbol, timeframe,
         window_start, window_end, bars)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb)
      ON CONFLICT (signal_id, event, timeframe) DO UPDATE SET
        captured_at = excluded.captured_at,
        symbol = excluded.symbol,
        window_start = excluded.window_start,
        window_end = excluded.window_end,
        bars = excluded.bars
      """,
      signal_id,
      event,
      captured_at,
      symbol,
      timeframe,
      window_start,
      window_end,
      json.dumps(bars),
    )


async def _safe_snapshot_manual_chart(
  *,
  signal_id: int,
  event: str,
  ts: int,
  symbol: str = "XAU",
) -> None:
  """Never fail the Telegram/fill path if Redis or chart write is empty."""
  try:
    from app.signals.manual_algo_chart import snapshot_manual_algo_chart
    await snapshot_manual_algo_chart(
      signal_id=signal_id,
      event=event,
      ts=ts,
      symbol=symbol,
    )
  except Exception:
    log.exception(
      "manual_algo_chart snapshot failed signal=%s event=%s",
      signal_id,
      event,
    )


async def get_manual_signal(row_id: int) -> dict | None:
  """Return one signal by primary key, regardless of lifecycle state."""
  async with _connect() as db:
    row = await db.fetchrow(
      "SELECT * FROM manual_signals WHERE id = $1", row_id,
    )
  return _decode_signal(row) if row else None


async def undo_last_close_leg(row_id: int) -> dict | None:
  """Undo the latest close booking and leave the signal open again.

  Used for operator mistakes: the trade was marked closed in the bot, but is
  still running in reality. If the signal had partial legs, only the most
  recent leg is removed so earlier intentional scale-outs remain intact.
  Final-close accounting rows linked to the signal are removed from pips_log.
  """
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 FOR UPDATE", row_id,
      )
      if row is None or row["status"] == "cancelled":
        return None

      legs = json.loads(row["legs"] or "[]")
      if row["status"] == "open" and not legs:
        return None

      restored_leg = legs.pop() if legs else None
      remaining = max(
        0.0,
        1.0 - sum(float(leg["frac"]) for leg in legs),
      )
      await db.execute(
        "UPDATE manual_signals "
        "SET status = 'open', result_pips = NULL, closed_at = NULL, "
        "legs = $1 WHERE id = $2",
        json.dumps(legs), row_id,
      )
      await db.execute(
        "DELETE FROM pips_log WHERE signal_id = $1", row_id,
      )
    return {
      **_decode_signal(row),
      "status": "open",
      "result_pips": None,
      "closed_at": None,
      "legs": legs,
      "restored_leg": restored_leg,
      "remaining": remaining,
      "previous_status": row["status"],
    }


async def get_manual_signal_any_by_channel_id(
  channel_message_id: int,
) -> dict | None:
  """Return a signal by channel message id, regardless of lifecycle state."""
  async with _connect() as db:
    row = await db.fetchrow(
      "SELECT * FROM manual_signals WHERE channel_message_id = $1",
      channel_message_id,
    )
  return _decode_signal(row) if row else None


def signal_root(signal: dict) -> int:
  """Return the single-hop root id for a signal or re-entry round."""
  return signal.get("parent_id") or signal["id"]


async def get_signal_cluster(row_id: int) -> list[dict]:
  """Return the root and all linked re-entry rounds for one signal."""
  source = await get_manual_signal(row_id)
  if source is None:
    return []
  root_id = signal_root(source)
  async with _connect() as db:
    rows = await db.fetch(
      "SELECT * FROM manual_signals "
      "WHERE id = $1 OR parent_id = $2 "
      "ORDER BY CASE WHEN id = $3 THEN 0 ELSE 1 END, ts ASC, id ASC",
      root_id, root_id, root_id,
    )
  return [_decode_signal(row) for row in rows]


async def update_setup(
  row_id: int,
  setup_type: str,
  confluence: int | None,
) -> bool:
  """Set or replace setup metadata on any signal."""
  async with _connect() as db:
    status = await db.execute(
      "UPDATE manual_signals SET setup_type = $1, confluence = $2 WHERE id = $3",
      setup_type.lower(), confluence, row_id,
    )
  return _rowcount(status) > 0


async def set_note(row_id: int, note: str) -> bool:
  """Set or replace the journal note on any signal."""
  async with _connect() as db:
    status = await db.execute(
      "UPDATE manual_signals SET note = $1 WHERE id = $2",
      note, row_id,
    )
  return _rowcount(status) > 0


async def mark_filled(row_id: int) -> dict | None:
  """Mark a pending open signal filled and return its pre-update row."""
  await expire_unfilled_pending_signals()
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals "
        "WHERE id = $1 AND status = 'open' AND fill_state = 'pending' "
        "FOR UPDATE",
        row_id,
      )
      if row is None:
        return None
      await db.execute(
        "UPDATE manual_signals SET fill_state = 'filled', filled_at = $1 "
        "WHERE id = $2 AND status = 'open' AND fill_state = 'pending'",
        int(time.time()), row_id,
      )
    return dict(row)


async def close_leg(
  row_id: int,
  pips: int,
  frac: float | None = None,
) -> dict | None:
  """Book one scale-out leg and close the signal when no size remains."""
  snapshot_close: tuple[int, int, str] | None = None
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 AND status = 'open' "
        "FOR UPDATE",
        row_id,
      )
      if row is None:
        return None

      legs = json.loads(row["legs"] or "[]")
      used = sum(float(leg["frac"]) for leg in legs)
      remaining = max(0.0, 1.0 - used)
      close_frac = remaining if frac is None else frac
      result_base = {
        "id": row["id"],
        "channel_message_id": row["channel_message_id"],
        "daily_seq": row["daily_seq"],
        "symbol": row["symbol"],
        "visibility": row["visibility"],
      }
      if close_frac <= 0 or close_frac > remaining + _LEG_EPSILON:
        return {
          **result_base,
          "error": "exceeds_remaining",
          "remaining": remaining,
        }

      now = int(time.time())
      legs.append({"frac": close_frac, "pips": pips, "ts": now})
      new_remaining = 1.0 - sum(float(leg["frac"]) for leg in legs)
      # Journal /trade_stats uses the highest TP/pips reached, not a
      # volume-fraction weighted blend that dilutes booked targets with a
      # later BE residual.
      achieved = legs_achieved_pips(legs)
      if new_remaining <= _LEG_EPSILON:
        await db.execute(
          "UPDATE manual_signals SET status = 'closed', result_pips = $1, "
          "closed_at = $2, legs = $3 WHERE id = $4 AND status = 'open'",
          achieved, now, json.dumps(legs), row_id,
        )
        snapshot_close = (int(row_id), now, str(row["symbol"] or "XAU"))
        result = {
          **result_base,
          "closed": True,
          "net": achieved,
          "remaining": 0.0,
          "frac": close_frac,
        }
      else:
        await db.execute(
          "UPDATE manual_signals SET legs = $1 "
          "WHERE id = $2 AND status = 'open'",
          json.dumps(legs), row_id,
        )
        result = {
          **result_base,
          "closed": False,
          "net": achieved,
          "remaining": new_remaining,
          "frac": close_frac,
        }
  if snapshot_close is not None:
    await _safe_snapshot_manual_chart(
      signal_id=snapshot_close[0],
      event="closed",
      ts=snapshot_close[1],
      symbol=snapshot_close[2],
    )
  return result


async def finalize_manual_group(
  row_id: int,
  result_pips: int,
) -> dict | None:
  """Close a manual /algo signal using AutoTradeEngine.cs's own final,
  authoritative group result (its ``group_result`` event's
  ``group_realized_pips``), bypassing ``close_leg``'s frac-accumulation
  ledger entirely.

  A manual /algo signal can be several independent entry legs (shallow/
  mid/deep, each its own broker position filled at its own price) closing
  together off one shared owner stop. For **losses**, prefer
  ``group_realized_pips`` (AutoTradeEngine.cs's volume-weighted total
  across independently-priced entry legs — 2026-08-19: a 3-leg SELL must
  not report -26 when the true blended loss was -47). For **wins**,
  channel TP cards already booked via ``close_leg`` must not be downgraded
  on the close line — ``legs_achieved_pips`` keeps the highest TP reached
  (e.g. TP4 +160 from the deep fill) even when ``group_realized_pips``
  from the last shallow leg prints +130.
  """
  now = int(time.time())
  snapshot_close: tuple[int, int, str] | None = None
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 AND status = 'open' "
        "FOR UPDATE",
        row_id,
      )
      if row is None:
        return None
      legs = json.loads(row["legs"] or "[]")
      legs.append({"frac": 1.0, "pips": result_pips, "ts": now})
      # Channel TP cards already booked the highest target reached; the
      # close line must never report a lower number than those legs (e.g.
      # group_realized_pips from the last shallow leg after TP4 printed
      # +160 from the deep fill).
      achieved = legs_achieved_pips(legs)
      await db.execute(
        "UPDATE manual_signals SET status = 'closed', result_pips = $1, "
        "closed_at = $2, legs = $3 WHERE id = $4 AND status = 'open'",
        achieved, now, json.dumps(legs), row_id,
      )
      snapshot_close = (int(row_id), now, str(row["symbol"] or "XAU"))
  if snapshot_close is not None:
    await _safe_snapshot_manual_chart(
      signal_id=snapshot_close[0],
      event="closed",
      ts=snapshot_close[1],
      symbol=snapshot_close[2],
    )
  return {
    "id": row["id"],
    "channel_message_id": row["channel_message_id"],
    "daily_seq": row["daily_seq"],
    "symbol": row["symbol"],
    "visibility": row["visibility"],
    "closed": True,
    "net": achieved,
    "remaining": 0.0,
    "frac": 1.0,
  }


async def update_sl(row_id: int, price: float) -> dict | None:
  """Move the stop loss on an open signal and return its previous row."""
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 AND status = 'open' "
        "FOR UPDATE",
        row_id,
      )
      if row is None:
        return None
      await db.execute(
        "UPDATE manual_signals SET sl = $1 WHERE id = $2 AND status = 'open'",
        price, row_id,
      )
    return dict(row)


async def update_pending_levels(
  row_id: int,
  *,
  entry: float | None = None,
  entry_end: float | None = None,
  sl: float | None = None,
  tps: list[float] | None = None,
) -> dict | None:
  """Rewrite entry/SL/TPs on an unfilled open signal; return the updated row.

  Only ``status=open`` + ``fill_state=pending`` rows are eligible. When SL
  changes, ``original_sl`` tracks the new stop so reopen/BE stay consistent.
  """
  if entry is None and entry_end is None and sl is None and tps is None:
    return None
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 AND status = 'open' "
        "AND fill_state = 'pending' FOR UPDATE",
        row_id,
      )
      if row is None:
        return None
      next_entry = float(row["entry"] if entry is None else entry)
      next_end = row["entry_end"] if entry_end is None else entry_end
      if next_end is None:
        next_end = next_entry
      next_end = float(next_end)
      if next_entry > next_end:
        next_entry, next_end = next_end, next_entry
      next_sl = float(row["sl"] if sl is None else sl)
      next_tps = (
        list(tps)
        if tps is not None
        else json.loads(row["tps"] or "[]")
      )
      await db.execute(
        "UPDATE manual_signals SET entry = $1, entry_end = $2, sl = $3, "
        "original_sl = CASE WHEN $4 THEN $3 ELSE original_sl END, "
        "tps = $5 WHERE id = $6 AND status = 'open' "
        "AND fill_state = 'pending'",
        next_entry,
        next_end,
        next_sl,
        sl is not None,
        json.dumps(next_tps),
        row_id,
      )
      updated = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1", row_id,
      )
  return _decode_signal(updated) if updated else None


async def clear_signal_posts(signal_id: int) -> None:
  """Drop persisted post rows so broadcast_entry can post fresh cards."""
  async with _connect() as db:
    await db.execute(
      "DELETE FROM signal_posts WHERE signal_id = $1", signal_id,
    )


async def set_execution_intent(
  signal_id: int,
  *,
  intent_id: str,
  status: str,
  revision: int,
) -> dict | None:
  """Attach a freshly published ManualTradeIntent to its signal row.

  Returns the updated row, or ``None`` if ``signal_id`` does not exist.
  """
  async with _connect() as db:
    row = await db.fetchrow(
      "UPDATE manual_signals SET execution_intent_id = $1, "
      "execution_status = $2, execution_revision = $3, algo_armed = TRUE "
      "WHERE id = $4 RETURNING *",
      intent_id, status, revision, signal_id,
    )
  return _decode_signal(row) if row else None


async def set_execution_status(
  signal_id: int,
  status: str,
  *,
  error: str | None = None,
) -> dict | None:
  """Update the execution lifecycle status (and optional error) on a signal.

  Returns the updated row, or ``None`` if ``signal_id`` does not exist.
  """
  async with _connect() as db:
    clear_armed = status in {"cancelled", "expired", "rejected"}
    row = await db.fetchrow(
      "UPDATE manual_signals SET execution_status = $1, execution_error = $2, "
      "algo_armed = CASE WHEN $3 AND broker_position_id IS NULL "
      "THEN FALSE ELSE algo_armed END WHERE id = $4 RETURNING *",
      status, error, clear_armed, signal_id,
    )
  return _decode_signal(row) if row else None


async def set_execution_fill(
  signal_id: int,
  *,
  broker_position_id: int,
  broker_fill_price: float,
) -> dict | None:
  """Record a manual-algo limit order's real broker fill.

  Called once per FILLED ENTRY LEG (from the reconcile loop) when
  AutoTradeEngine.cs's fill adoption reconstructs a position and publishes
  its "manual_opened" event - a manual /algo signal can be several
  independent entry legs (the shallow/mid/deep split), so this fires more
  than once for the same signal_id.

  ``broker_fill_price`` keeps the **shallow** filled entry (the approved
  worst-case risk reference: lower for SELL, higher for BUY). Mid/deep
  fills retain their own prices in executor state and lifecycle events for
  actual weighted P&L; this one-column signal fallback must never shrink the
  owner stop distance merely because a deeper clip filled. The position id
  still keeps the first fill via COALESCE (owner close routes by intent
  group, not this column).

  Returns the updated row, or ``None`` if ``signal_id`` does not exist.
  """
  async with _connect() as db:
    row = await db.fetchrow(
      """
      UPDATE manual_signals SET
        execution_status = 'filled',
        algo_armed = TRUE,
        trade_stream = 'algo_manual',
        broker_position_id = COALESCE(broker_position_id, $1),
        broker_fill_price = CASE
          WHEN broker_fill_price IS NULL THEN $2
          WHEN UPPER(action) = 'SELL' AND $2 < broker_fill_price THEN $2
          WHEN UPPER(action) = 'BUY' AND $2 > broker_fill_price THEN $2
          ELSE broker_fill_price
        END
      WHERE id = $3
      RETURNING *
      """,
      str(broker_position_id), broker_fill_price, signal_id,
    )
  decoded = _decode_signal(row) if row else None
  if decoded is not None:
    await _safe_snapshot_manual_chart(
      signal_id=int(signal_id),
      event="filled",
      ts=int(time.time()),
      symbol=str(decoded.get("symbol") or "XAU"),
    )
  return decoded


async def get_signal_by_execution_intent_id(intent_token: str) -> dict | None:
  """Look up a manual signal by its ``execution_intent_id``.

  Tolerates the truncated identity cTrader comments carry: comment fields
  are capped at 100 chars broker-side, so AutoTradeEngine.cs embeds only
  ``CandidateToken(intent_id)`` (the first 10 characters) in a manual-algo
  position/order comment — the same truncation convention every other
  candidate type in this codebase already accepts for comment-based
  identity matching. Matching by prefix means either the full
  ``execution_intent_id`` or that truncated token resolves the same row.
  On the rare (and, for this single-owner bot, extremely unlikely) case of
  two signals sharing a 10-character prefix, the most recently created
  match wins.
  """
  async with _connect() as db:
    row = await db.fetchrow(
      "SELECT * FROM manual_signals WHERE execution_intent_id LIKE $1 || '%' "
      "ORDER BY id DESC LIMIT 1",
      intent_token[:10],
    )
  return _decode_signal(row) if row else None


async def get_manual_signal_by_channel_id(channel_message_id: int) -> dict | None:
  """Look up an open manual signal by its Telegram channel message_id."""
  async with _connect() as db:
    row = await db.fetchrow(
      "SELECT * FROM manual_signals "
      "WHERE channel_message_id = $1 AND status = 'open'",
      channel_message_id,
    )
    return dict(row) if row else None


async def close_manual_signal(row_id: int, result_pips: int) -> dict | None:
  """Mark a signal as closed and record the pip result.

  Returns:
    The row dict as it was *before* the update (so ``channel_message_id``
    is available for the channel reply), or ``None`` if the signal was not
    found or was already closed/cancelled.
  """
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 AND status = 'open' "
        "FOR UPDATE",
        row_id,
      )
      if row is None:
        return None
      closed_at = int(time.time())
      await db.execute(
        "UPDATE manual_signals SET status = 'closed', result_pips = $1, "
        "closed_at = $2 WHERE id = $3",
        result_pips, closed_at, row_id,
      )
  await _safe_snapshot_manual_chart(
    signal_id=int(row_id),
    event="closed",
    ts=closed_at,
    symbol=str(row["symbol"] or "XAU"),
  )
  return dict(row)


async def cancel_manual_signal_by_channel_id(channel_message_id: int) -> dict | None:
  """Cancel an open signal identified by the Telegram channel message_id."""
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals "
        "WHERE channel_message_id = $1 AND status = 'open' "
        "FOR UPDATE",
        channel_message_id,
      )
      if row is None:
        return None
      row = dict(row)
      await db.execute(
        "UPDATE manual_signals SET status = 'cancelled', closed_at = $1 "
        "WHERE id = $2",
        int(time.time()), row["id"],
      )
    return row


async def cancel_manual_signal(row_id: int) -> dict | None:
  """Cancel an open signal by its primary key."""
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 AND status = 'open' "
        "FOR UPDATE",
        row_id,
      )
      if row is None:
        return None
      await db.execute(
        "UPDATE manual_signals SET status = 'cancelled', closed_at = $1 "
        "WHERE id = $2",
        int(time.time()), row_id,
      )
    return dict(row)


async def delete_manual_signal(row_id: int) -> dict | None:
  """Hard-delete a mistyped signal, unlike ``cancel`` which keeps the record.

  Removes the row plus its delivered posts and accounting rows, and returns
  the deleted signal with a ``posts`` list so the caller can also delete the
  channel messages. Returns ``None`` if the signal is gone, or a dict with
  ``{"error": "has_rounds"}`` when re-entry rounds point at it — deleting then
  would orphan later rounds, so cancel (or delete the rounds first) instead.
  """
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 FOR UPDATE", row_id,
      )
      if row is None:
        return None
      child = await db.fetchrow(
        "SELECT 1 FROM manual_signals WHERE parent_id = $1 LIMIT 1", row_id,
      )
      if child is not None:
        return {"error": "has_rounds"}
      posts = await db.fetch(
        "SELECT * FROM signal_posts WHERE signal_id = $1", row_id,
      )
      await db.execute("DELETE FROM pips_log WHERE signal_id = $1", row_id)
      await db.execute(
        "DELETE FROM manual_algo_charts WHERE signal_id = $1", row_id,
      )
      await db.execute("DELETE FROM signal_posts WHERE signal_id = $1", row_id)
      await db.execute("DELETE FROM manual_signals WHERE id = $1", row_id)
    return {**_decode_signal(row), "posts": [dict(post) for post in posts]}
