"""Complete Canonical Catalog V2 configuration domain. """
from pydantic import Field
from pydantic import model_validator
from app.configuration.metadata import ConfigKind
from app.configuration.metadata import ConfigOwner
from app.configuration.metadata import ConfigUnit
from app.configuration.metadata import ContextDefault
from app.configuration.metadata import DefaultContext
from app.configuration.metadata import MismatchPolicy
from app.configuration.metadata import ReloadPolicy
from app.configuration.metadata import RiskClassification
from app.configuration.metadata import config_field
from app.configuration.models.base import FrozenConfigModel

class AnalysisMeasurementsConfig(FrozenConfigModel):
    alert_overlap_suppress: float = config_field(0.5, canonical_env='ALERT_OVERLAP_SUPPRESS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),), validation_summary='Pydantic required/type coercion only')
    coil_contract: float = config_field(0.8, canonical_env='COIL_CONTRACT', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.8),), validation_summary='Pydantic required/type coercion only')
    eq_band: float = config_field(0.1, canonical_env='EQ_BAND', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.1),), validation_summary='Pydantic required/type coercion only')
    inducement_band_atr: float = config_field(0.3, canonical_env='INDUCEMENT_BAND_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.3),), validation_summary='Pydantic required/type coercion only')
    max_merged_zone_atr: float = config_field(3.0, canonical_env='MAX_MERGED_ZONE_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3.0),), validation_summary='Pydantic required/type coercion only')
    regime_chop_alert_share: float = config_field(0.75, canonical_env='REGIME_CHOP_ALERT_SHARE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.75),), validation_summary='Pydantic required/type coercion only')
    scanner_conflict_overlap: float = config_field(0.5, canonical_env='SCANNER_CONFLICT_OVERLAP', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Operational environment option SCANNER_CONFLICT_OVERLAP.', validation_summary='direct environment read or deployment parser', deprecated=True, terminal_deprecation_reason='No runtime consumer; retained as Phase 1 audit evidence.')
    strict_pd_gate: bool = config_field(False, canonical_env='STRICT_PD_GATE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    tp_min_spacing_atr: float = config_field(0.5, canonical_env='TP_MIN_SPACING_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),), validation_summary='Pydantic required/type coercion only')

class AnalysisDetectorsScoringConfig(FrozenConfigModel):
    coil: float = config_field(1.5, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.detectors.scoring.coil.', validation_summary='none; source constant')

class AnalysisDetectorsReactionConfig(FrozenConfigModel):
    maximum_distance_atr: float = config_field(1.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.detectors.reaction.maximum_distance_atr.', validation_summary='none; source constant')

class AnalysisDetectorsStarThresholdsConfig(FrozenConfigModel):
    three: float = config_field(12.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.detectors.star_thresholds.three.', validation_summary='none; source constant')
    two: float = config_field(8.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.detectors.star_thresholds.two.', validation_summary='none; source constant')

class AnalysisDetectorsConfig(FrozenConfigModel):
    reaction: AnalysisDetectorsReactionConfig = Field(default_factory=AnalysisDetectorsReactionConfig)
    scoring: AnalysisDetectorsScoringConfig = Field(default_factory=AnalysisDetectorsScoringConfig)
    star_thresholds: AnalysisDetectorsStarThresholdsConfig = Field(default_factory=AnalysisDetectorsStarThresholdsConfig)

class AnalysisDisplacementConfig(FrozenConfigModel):
    atr_mult: float = config_field(1.5, canonical_env='DISPLACEMENT_ATR_MULT', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.5),), validation_summary='Pydantic required/type coercion only')
    body_fraction: float = config_field(0.6, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.displacement.body_fraction.', validation_summary='none; source constant')
    minimum_range_atr: float = config_field(1.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.displacement.minimum_range_atr.', validation_summary='none; source constant')

class AnalysisMarketMapConfig(FrozenConfigModel):
    band_max_atr: float = config_field(2.0, canonical_env='MAP_BAND_MAX_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2.0),), validation_summary='Pydantic required/type coercion only')
    change_min: float = config_field(1.0, canonical_env='MAP_CHANGE_MIN', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.0),), validation_summary='Pydantic required/type coercion only')
    fallback_radius_price: float = config_field(30.0, canonical_env='MAP_FALLBACK_RADIUS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (price).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 30.0),), validation_summary='Pydantic required/type coercion only')
    major_score: float = config_field(12.0, canonical_env='MAP_MAJOR_SCORE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 12.0),), validation_summary='Pydantic required/type coercion only')
    max_distance_atr: float = config_field(15.0, canonical_env='MAP_MAX_DISTANCE_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 15.0),), validation_summary='Pydantic required/type coercion only')
    max_per_side: int = config_field(4, canonical_env='MAP_MAX_PER_SIDE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 4),), validation_summary='Pydantic required/type coercion only')
    max_touches: int = config_field(4, canonical_env='MAP_MAX_TOUCHES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Zone touches before it drops out of the actionable opposing-barrier pool (count). Was 2 - a major/breaker/flip zone still being actively retested lost its opposing-barrier status after its 2nd touch, letting a SELL trade through with no real room-check against it (04 Aug 23:31 incident: SL loss reacting off a demand zone the map had correctly been blocking against 10 minutes earlier). Matches min_level_touches (4), which already treats 4 as the significance bar for levels.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 4),), validation_summary='Pydantic required/type coercion only')
    min_level_touches: int = config_field(4, canonical_env='MAP_MIN_LEVEL_TOUCHES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 4),), validation_summary='Pydantic required/type coercion only')
    min_per_side: int = config_field(2, canonical_env='MAP_MIN_PER_SIDE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    min_zone_score: float = config_field(6.0, canonical_env='MAP_MIN_ZONE_SCORE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 6.0),), validation_summary='Pydantic required/type coercion only')
    scalp_radius_price: float = config_field(15.0, canonical_env='MAP_SCALP_RADIUS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (price).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 15.0),), validation_summary='Pydantic required/type coercion only')
    scan_interval_minutes: int = config_field(60, canonical_env='MAP_SCAN_INTERVAL_MINUTES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MINUTES, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (minutes).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 60),), validation_summary='Pydantic required/type coercion only')
    session_band_atr: float = config_field(0.1, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.market_map.session_band_atr.', validation_summary='none; source constant')

class AnalysisTrendlinesConfig(FrozenConfigModel):
    dedup_slope_percent: float = config_field(0.2, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.PERCENT, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.trendlines.dedup_slope_percent.', validation_summary='none; source constant')
    dedup_value_atr: float = config_field(0.5, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.trendlines.dedup_value_atr.', validation_summary='none; source constant')
    maximum_slope_atr: float = config_field(0.15, canonical_env='TL_MAX_SLOPE_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.15),), validation_summary='Pydantic required/type coercion only')
    minimum_touches: int = config_field(3, canonical_env='TL_MIN_TOUCHES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),), validation_summary='Pydantic required/type coercion only')
    tolerance_atr: float = config_field(0.3, canonical_env='TL_TOL_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.3),), validation_summary='Pydantic required/type coercion only')

class AnalysisZonesScoringConfig(FrozenConfigModel):
    fresh: float = config_field(3.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.scoring.fresh.', validation_summary='none; source constant')
    grade_a_grab: float = config_field(2.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.scoring.grade_a_grab.', validation_summary='none; source constant')
    higher_timeframe: float = config_field(3.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.scoring.higher_timeframe.', validation_summary='none; source constant')
    key_level: float = config_field(2.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.scoring.key_level.', validation_summary='none; source constant')
    liquidity: float = config_field(2.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.scoring.liquidity.', validation_summary='none; source constant')
    premium_discount: float = config_field(2.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.scoring.premium_discount.', validation_summary='none; source constant')
    round_number: float = config_field(1.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.scoring.round_number.', validation_summary='none; source constant')
    session_level: float = config_field(2.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.scoring.session_level.', validation_summary='none; source constant')
    single_touch: float = config_field(1.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.scoring.single_touch.', validation_summary='none; source constant')
    source_cap: float = config_field(5.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.scoring.source_cap.', validation_summary='none; source constant')
    trendline: float = config_field(1.5, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.scoring.trendline.', validation_summary='none; source constant')

class AnalysisZonesReconciliationConfig(FrozenConfigModel):
    maximum_affected_fraction: float = config_field(0.2, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.reconciliation.maximum_affected_fraction.', validation_summary='none; source constant')
    minimum_overlap: float = config_field(0.5, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.reconciliation.minimum_overlap.', validation_summary='none; source constant')
    minimum_remainder_price: float = config_field(2.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.PRICE, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.reconciliation.minimum_remainder_price.', validation_summary='none; source constant')
    minimum_sample: int = config_field(5, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.COUNT, risk=RiskClassification.ANALYSIS_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at analysis.zones.reconciliation.minimum_sample.', validation_summary='none; source constant')

class AnalysisZonesDiscoveryConfig(FrozenConfigModel):
    maximum_width_atr: float = config_field(1.5, canonical_env='MAX_ZONE_WIDTH_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.EXECUTION_SAFETY, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.5),), validation_summary='Pydantic required/type coercion only')

class AnalysisZonesSymbolContractConfig(FrozenConfigModel):
    major_maximum_width_price: float = config_field(10.0, canonical_env='XAU_MAJOR_ZONE_MAX_WIDTH_PRICE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (price).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 10.0),), validation_summary='Pydantic type coercion + Settings cross-field model validator')
    minimum_width_price: float = config_field(3.0, canonical_env='XAU_ZONE_MIN_WIDTH_PRICE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (price).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3.0),), validation_summary='Pydantic type coercion + Settings cross-field model validator')
    preferred_maximum_width_price: float = config_field(6.0, canonical_env='XAU_ZONE_PREFERRED_MAX_WIDTH_PRICE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (price).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 6.0),), validation_summary='Pydantic type coercion + Settings cross-field model validator')
    preferred_minimum_width_price: float = config_field(3.0, canonical_env='XAU_ZONE_PREFERRED_MIN_WIDTH_PRICE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (price).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3.0),), validation_summary='Pydantic type coercion + Settings cross-field model validator')

    @model_validator(mode='after')
    def validate_width_order(self):
        if not 0 < self.minimum_width_price <= self.preferred_minimum_width_price <= self.preferred_maximum_width_price <= self.major_maximum_width_price:
            raise ValueError('XAU zone widths must satisfy minimum <= preferred minimum <= preferred maximum <= major maximum')
        return self

class AnalysisZonesConfluenceConfig(FrozenConfigModel):
    merge_gap_price: float = config_field(1.0, canonical_env='ZONE_MERGE_GAP', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (price).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.0),), validation_summary='Pydantic required/type coercion only')
    technique_bonus_score: float = config_field(2.5, canonical_env='CONFLUENCE_TECHNIQUE_BONUS_SCORE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Per extra overlapping technique added to Confluence Zone band score.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2.5),), validation_summary='Pydantic required/type coercion only')

class AnalysisZonesConfig(FrozenConfigModel):
    alert_ttl: int = config_field(14400, canonical_env='ZONE_ALERT_TTL', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SECONDS, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (seconds).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 14400),), validation_summary='Pydantic required/type coercion only')
    confluence: AnalysisZonesConfluenceConfig = Field(default_factory=AnalysisZonesConfluenceConfig)
    discovery: AnalysisZonesDiscoveryConfig = Field(default_factory=AnalysisZonesDiscoveryConfig)
    merge_max_width: float = config_field(6.0, canonical_env='ZONE_MERGE_MAX_WIDTH', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (price).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 6.0),), validation_summary='Pydantic required/type coercion only')
    merge_overlap: float = config_field(0.5, canonical_env='ZONE_MERGE_OVERLAP', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),), validation_summary='Pydantic required/type coercion only')
    reconciliation: AnalysisZonesReconciliationConfig = Field(default_factory=AnalysisZonesReconciliationConfig)
    scoring: AnalysisZonesScoringConfig = Field(default_factory=AnalysisZonesScoringConfig)
    symbol_contract: AnalysisZonesSymbolContractConfig = Field(default_factory=AnalysisZonesSymbolContractConfig)
    width: str = config_field('body', canonical_env='ZONE_WIDTH', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'body'),), validation_summary='Pydantic required/type coercion only')

class AnalysisAtrConfig(FrozenConfigModel):
    length: int = config_field(14, canonical_env='ATR_LENGTH', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 14),), validation_summary='Pydantic required/type coercion only')

class AnalysisBreakoutConfig(FrozenConfigModel):
    accept_bars: int = config_field(2, canonical_env='BREAKOUT_ACCEPT_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    buffer_atr: float = config_field(0.1, canonical_env='BREAKOUT_BUFFER_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.1),), validation_summary='Pydantic required/type coercion only')
    max_age_bars: int = config_field(6, canonical_env='BREAKOUT_MAX_AGE_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 6),), validation_summary='Pydantic required/type coercion only')

class AnalysisRegimeChopConfig(FrozenConfigModel):
    edge_frac: float = config_field(0.25, canonical_env='CHOP_EDGE_FRAC', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.25),), validation_summary='Pydantic required/type coercion only')
    filter_enabled: bool = config_field(True, canonical_env='CHOP_FILTER_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    lookback: int = config_field(24, canonical_env='CHOP_LOOKBACK', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 24),), validation_summary='Pydantic required/type coercion only')
    range_atr: float = config_field(4.0, canonical_env='CHOP_RANGE_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 4.0),), validation_summary='Pydantic required/type coercion only')

class AnalysisRegimeConfig(FrozenConfigModel):
    chop: AnalysisRegimeChopConfig = Field(default_factory=AnalysisRegimeChopConfig)

class AnalysisLevelsConfig(FrozenConfigModel):
    equal_tol_atr: float = config_field(0.15, canonical_env='EQUAL_TOL_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.15),), validation_summary='Pydantic required/type coercion only')
    level_cluster_atr: float = config_field(0.5, canonical_env='LEVEL_CLUSTER_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),), validation_summary='Pydantic required/type coercion only')
    minimum_key_touches: int = config_field(2, canonical_env='KEY_LEVEL_MIN_TOUCHES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    round_step: float = config_field(5.0, canonical_env='ROUND_STEP', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (price).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5.0),), validation_summary='Pydantic required/type coercion only')

class AnalysisTriggersM1Config(FrozenConfigModel):
    patterns: str = config_field('wick_rejection,body_close,strong_close,pin_bar,engulfing,hammer', canonical_env='M1_TRIGGER_PATTERNS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.STRING, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'wick_rejection,body_close,strong_close,pin_bar,engulfing,hammer'),), validation_summary='Pydantic required/type coercion only')
    strong_close_pct: float = config_field(0.2, canonical_env='M1_TRIGGER_STRONG_CLOSE_PCT', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PERCENT, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (percent).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.2),), validation_summary='Pydantic required/type coercion only')
    wick_fraction: float = config_field(0.5, canonical_env='M1_TRIGGER_WICK_FRACTION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),), validation_summary='Pydantic required/type coercion only')

class AnalysisTriggersConfig(FrozenConfigModel):
    m1: AnalysisTriggersM1Config = Field(default_factory=AnalysisTriggersM1Config)

class AnalysisMomentumConfig(FrozenConfigModel):
    body_frac: float = config_field(0.6, canonical_env='MOMENTUM_BODY_FRAC', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.6),), validation_summary='Pydantic required/type coercion only')
    lookback: int = config_field(8, canonical_env='MOMENTUM_LOOKBACK', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 8),), validation_summary='Pydantic required/type coercion only')
    velocity_lookback: int = config_field(8, canonical_env='MOMENTUM_VELOCITY_LOOKBACK', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Bars for ATR-normalized velocity/acceleration.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 8),), validation_summary='Pydantic required/type coercion only')
    velocity_bull_threshold: float = config_field(0.15, canonical_env='MOMENTUM_VELOCITY_BULL_THRESHOLD', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Minimum v for bull state.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.15),), validation_summary='Pydantic required/type coercion only')
    velocity_bear_threshold: float = config_field(-0.15, canonical_env='MOMENTUM_VELOCITY_BEAR_THRESHOLD', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Maximum v for bear state.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, -0.15),), validation_summary='Pydantic required/type coercion only')
    va_gate_enabled: bool = config_field(False, canonical_env='MOMENTUM_VA_GATE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='When true, Momentum Ride requires velocity aligned with direction.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')


class AnalysisFibonacciConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='FIBONACCI_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Compute swing Fib ladders and soft confluence.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    epsilon_atr: float = config_field(0.15, canonical_env='FIBONACCI_EPSILON_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='ATR band for fib_touch matches.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.15),), validation_summary='Pydantic required/type coercion only')
    confluence_weight: float = config_field(2.5, canonical_env='FIBONACCI_CONFLUENCE_WEIGHT', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SCORE, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Soft confluence weight when entry/level touches a Fib.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2.5),), validation_summary='Pydantic required/type coercion only')
    deep_discount: float = config_field(0.382, canonical_env='FIBONACCI_DEEP_DISCOUNT', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='PD position at or below this is deep_discount.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.382),), validation_summary='Pydantic required/type coercion only')
    deep_premium: float = config_field(0.618, canonical_env='FIBONACCI_DEEP_PREMIUM', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='PD position at or above this is deep_premium.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.618),), validation_summary='Pydantic required/type coercion only')

class AnalysisTechniquesConfig(FrozenConfigModel):
    validation_enabled: bool = config_field(True, canonical_env='TECHNIQUE_VALIDATION_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Run validate_technique_instance when collecting technique instances.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class AnalysisRangesConfig(FrozenConfigModel):
    lookback: int = config_field(50, canonical_env='RANGE_LOOKBACK', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 50),), validation_summary='Pydantic required/type coercion only')

class AnalysisReactionsConfig(FrozenConfigModel):
    max_atr: float = config_field(0.5, canonical_env='REACTION_MAX_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),), validation_summary='Pydantic required/type coercion only')

class AnalysisLiquiditySweepConfig(FrozenConfigModel):
    body_frac: float = config_field(0.5, canonical_env='SWEEP_BODY_FRAC', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),), validation_summary='Pydantic required/type coercion only')
    react_bars: int = config_field(3, canonical_env='SWEEP_REACT_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),), validation_summary='Pydantic required/type coercion only')

class AnalysisLiquidityConfig(FrozenConfigModel):
    sweep: AnalysisLiquiditySweepConfig = Field(default_factory=AnalysisLiquiditySweepConfig)

class AnalysisSwingsZigzagConfig(FrozenConfigModel):
    atr_mult: float = config_field(1.0, canonical_env='ZIGZAG_ATR_MULT', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.0),), validation_summary='Pydantic required/type coercion only')
    pct: float = config_field(0.0, canonical_env='ZIGZAG_PCT', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PERCENT, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (percent).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.0),), validation_summary='Pydantic required/type coercion only')

class AnalysisSwingsConfig(FrozenConfigModel):
    fractal_size: int = config_field(2, canonical_env='SWING_FRACTAL_N', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.ANALYSIS_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    zigzag: AnalysisSwingsZigzagConfig = Field(default_factory=AnalysisSwingsZigzagConfig)

class AnalysisConfig(FrozenConfigModel):
    atr: AnalysisAtrConfig = Field(default_factory=AnalysisAtrConfig)
    breakout: AnalysisBreakoutConfig = Field(default_factory=AnalysisBreakoutConfig)
    detectors: AnalysisDetectorsConfig = Field(default_factory=AnalysisDetectorsConfig)
    displacement: AnalysisDisplacementConfig = Field(default_factory=AnalysisDisplacementConfig)
    levels: AnalysisLevelsConfig = Field(default_factory=AnalysisLevelsConfig)
    liquidity: AnalysisLiquidityConfig = Field(default_factory=AnalysisLiquidityConfig)
    market_map: AnalysisMarketMapConfig = Field(default_factory=AnalysisMarketMapConfig)
    measurements: AnalysisMeasurementsConfig = Field(default_factory=AnalysisMeasurementsConfig)
    momentum: AnalysisMomentumConfig = Field(default_factory=AnalysisMomentumConfig)
    fibonacci: AnalysisFibonacciConfig = Field(default_factory=AnalysisFibonacciConfig)
    ranges: AnalysisRangesConfig = Field(default_factory=AnalysisRangesConfig)
    reactions: AnalysisReactionsConfig = Field(default_factory=AnalysisReactionsConfig)
    regime: AnalysisRegimeConfig = Field(default_factory=AnalysisRegimeConfig)
    swings: AnalysisSwingsConfig = Field(default_factory=AnalysisSwingsConfig)
    techniques: AnalysisTechniquesConfig = Field(default_factory=AnalysisTechniquesConfig)
    trendlines: AnalysisTrendlinesConfig = Field(default_factory=AnalysisTrendlinesConfig)
    triggers: AnalysisTriggersConfig = Field(default_factory=AnalysisTriggersConfig)
    zones: AnalysisZonesConfig = Field(default_factory=AnalysisZonesConfig)
