"""Complete Canonical Catalog V2 configuration domain. """
from pydantic import Field
from pydantic import field_validator
from app.configuration.metadata import ConfigKind
from app.configuration.metadata import ConfigOwner
from app.configuration.metadata import ConfigUnit
from app.configuration.metadata import ContextDefault
from app.configuration.metadata import DefaultContext
from app.configuration.metadata import MismatchPolicy
from app.configuration.metadata import ReloadPolicy
from app.configuration.metadata import RiskClassification
from app.configuration.metadata import config_field
from app.configuration.models.base import FrozenConfigModel

class ContractAccountConfig(FrozenConfigModel):
    expected_broker: str = config_field('fpmarkets', canonical_env='AUTO_TRADE_EXPECTED_BROKER', deprecated_env_aliases=('CTRADER_EXPECTED_BROKER',), owner=ConfigOwner.SHARED, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.STRING, risk=RiskClassification.CROSS_SERVICE_CONTRACT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'fpmarkets'),), validation_summary='EnvironmentResolver.String + AutoTradeOptions.Validate')
    require_demo: bool = config_field(True, canonical_env='AUTO_TRADE_REQUIRE_DEMO_ACCOUNT', owner=ConfigOwner.SHARED, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.CROSS_SERVICE_CONTRACT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.Bool + AutoTradeOptions.Validate')

class ContractKeysConfig(FrozenConfigModel):
    config_health: str = config_field('auto_trade:config_health', canonical_env=None, owner=ConfigOwner.SHARED, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.CROSS_SERVICE_CONTRACT, kind=ConfigKind.PROTOCOL_CONSTANT, shared_with_ctrader=True, description='Config-like hardcoded value proposed at contract.keys.config_health.', validation_summary='none; source constant')
    ctrader_manifest: str = config_field('auto_trade:config_manifest:ctrader', canonical_env=None, owner=ConfigOwner.SHARED, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.CROSS_SERVICE_CONTRACT, kind=ConfigKind.PROTOCOL_CONSTANT, shared_with_ctrader=True, description='Config-like hardcoded value proposed at contract.keys.ctrader_manifest.', validation_summary='none; source constant')
    executor_readiness: str = config_field('auto_trade:executor_readiness', canonical_env=None, owner=ConfigOwner.SHARED, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.CROSS_SERVICE_CONTRACT, kind=ConfigKind.PROTOCOL_CONSTANT, shared_with_ctrader=True, description='Config-like hardcoded value proposed at contract.keys.executor_readiness.', validation_summary='none; source constant')
    python_manifest: str = config_field('auto_trade:config_manifest:python', canonical_env=None, owner=ConfigOwner.SHARED, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.CROSS_SERVICE_CONTRACT, kind=ConfigKind.PROTOCOL_CONSTANT, shared_with_ctrader=True, description='Config-like hardcoded value proposed at contract.keys.python_manifest.', validation_summary='none; source constant')
    tracked_positions: str = config_field('auto_trade:positions', canonical_env=None, owner=ConfigOwner.SHARED, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.CROSS_SERVICE_CONTRACT, kind=ConfigKind.PROTOCOL_CONSTANT, shared_with_ctrader=True, description='Config-like hardcoded value proposed at contract.keys.tracked_positions.', validation_summary='none; source constant')

class ContractVersionsConfig(FrozenConfigModel):
    candidate: int = config_field(6, canonical_env='AUTO_TRADE_CANDIDATE_CONTRACT_VERSION', owner=ConfigOwner.SHARED, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.VERSION, risk=RiskClassification.CROSS_SERVICE_CONTRACT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 6), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 6)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Int + AutoTradeOptions.Validate')
    config_manifest: int = config_field(2, canonical_env=None, owner=ConfigOwner.SHARED, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.VERSION, risk=RiskClassification.CROSS_SERVICE_CONTRACT, kind=ConfigKind.PROTOCOL_CONSTANT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Config-like hardcoded value proposed at contract.versions.config_manifest.', validation_summary='none; source constant')
    entry_plan: int = config_field(1, canonical_env=None, owner=ConfigOwner.SHARED, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.VERSION, risk=RiskClassification.CROSS_SERVICE_CONTRACT, kind=ConfigKind.PROTOCOL_CONSTANT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Config-like hardcoded value proposed at contract.versions.entry_plan.', validation_summary='none; source constant')
    stop_plan: int = config_field(3, canonical_env=None, owner=ConfigOwner.SHARED, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.VERSION, risk=RiskClassification.CROSS_SERVICE_CONTRACT, kind=ConfigKind.PROTOCOL_CONSTANT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Config-like hardcoded value proposed at contract.versions.stop_plan.', validation_summary='none; source constant')
    trade_plan: int = config_field(7, canonical_env=None, owner=ConfigOwner.SHARED, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.VERSION, risk=RiskClassification.CROSS_SERVICE_CONTRACT, kind=ConfigKind.PROTOCOL_CONSTANT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Config-like hardcoded value proposed at contract.versions.trade_plan.', validation_summary='none; source constant')

class ContractStreamsConfig(FrozenConfigModel):
    candidate_maximum_length: int = config_field(1000, canonical_env='AUTO_TRADE_STREAM_MAXLEN', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.CROSS_SERVICE_CONTRACT, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1000),), validation_summary='Pydantic required/type coercion only')
    candidates: str = config_field('auto_trade:candidates', canonical_env='AUTO_TRADE_CANDIDATE_STREAM', deprecated_env_aliases=('AUTO_TRADE_STREAM',), owner=ConfigOwner.SHARED, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.CROSS_SERVICE_CONTRACT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'auto_trade:candidates'), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'auto_trade:candidates')), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.String + AutoTradeOptions.Validate')
    events: str = config_field('auto_trade:events', canonical_env='AUTO_TRADE_EVENT_STREAM', owner=ConfigOwner.SHARED, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.CROSS_SERVICE_CONTRACT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'auto_trade:events'), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'auto_trade:events')), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.String + AutoTradeOptions.Validate')
    strategy_match_ready: str = config_field('auto_trade:strategy_match_ready', canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.CROSS_SERVICE_CONTRACT, kind=ConfigKind.PROTOCOL_CONSTANT, description='Config-like hardcoded value proposed at contract.streams.strategy_match_ready.', validation_summary='none; source constant')
    trade_plans: str = config_field('execution:trade_plans', canonical_env='AUTO_TRADE_TRADE_PLAN_STREAM', owner=ConfigOwner.SHARED, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.CROSS_SERVICE_CONTRACT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'execution:trade_plans'), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'execution:trade_plans')), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.String + AutoTradeOptions.Validate')

class ContractInstrumentConfig(FrozenConfigModel):
    canonical_symbol: str = config_field('XAU', canonical_env='AUTO_TRADE_CANONICAL_SYMBOL', owner=ConfigOwner.SHARED, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.CROSS_SERVICE_CONTRACT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'XAU'), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'XAU')), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.String + AutoTradeOptions.Validate')
    contract_units_per_lot: float = config_field(100.0, canonical_env='AUTO_TRADE_XAU_CONTRACT_SIZE', deprecated_env_aliases=('AUTO_TRADE_CONTRACT_SIZE',), owner=ConfigOwner.SHARED, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.CONTRACT_UNITS_PER_LOT, risk=RiskClassification.CROSS_SERVICE_CONTRACT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Controls  (contract_units_per_lot).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 100.0), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 100)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Decimal + AutoTradeOptions.Validate')
    pip_size: float = config_field(0.1, canonical_env='AUTO_TRADE_XAU_PIP_SIZE', deprecated_env_aliases=('AUTO_TRADE_PIP_SIZE',), owner=ConfigOwner.SHARED, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.CROSS_SERVICE_CONTRACT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Controls  (pips).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.1), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 0.1)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Decimal + AutoTradeOptions.Validate')
    price_digits: int = config_field(2, canonical_env='AUTO_TRADE_XAU_PRICE_DIGITS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.CROSS_SERVICE_CONTRACT, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    symbols: str = config_field('XAU', canonical_env='AUTO_TRADE_SYMBOLS', owner=ConfigOwner.SHARED, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.CROSS_SERVICE_CONTRACT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'XAU'), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'XAU')), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.StringList + AutoTradeOptions.Validate')

class ContractConfig(FrozenConfigModel):
    account: ContractAccountConfig = Field(default_factory=ContractAccountConfig)
    instrument: ContractInstrumentConfig = Field(default_factory=ContractInstrumentConfig)
    keys: ContractKeysConfig = Field(default_factory=ContractKeysConfig)
    mode: str = config_field('v7_only', canonical_env='AUTO_TRADE_CONTRACT_MODE', owner=ConfigOwner.SHARED, reload=ReloadPolicy.RESTART, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.CROSS_SERVICE_CONTRACT, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'v7_only'), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'v7_only'), ContextDefault(DefaultContext.CTRADER_CONSTRUCTOR, 'legacy_v6')), allowed_values=('v7_only',), validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.String + AutoTradeOptions.Validate', pattern='^v7_only$')

    @field_validator('mode', mode='before')
    @classmethod
    def normalize_mode(cls, value):
        return value.strip().lower() if isinstance(value, str) else value
    streams: ContractStreamsConfig = Field(default_factory=ContractStreamsConfig)
    versions: ContractVersionsConfig = Field(default_factory=ContractVersionsConfig)
