"""Complete inactive execution configuration domain."""

from decimal import Decimal

from pydantic import Field
from pydantic import field_validator
from pydantic import model_validator

from app.configuration.metadata import ConfigKind
from app.configuration.metadata import ConfigOwner
from app.configuration.metadata import ConfigUnit
from app.configuration.metadata import ContextDefault
from app.configuration.metadata import DefaultContext
from app.configuration.metadata import MismatchPolicy
from app.configuration.metadata import ReloadPolicy
from app.configuration.metadata import RiskClassification
from app.configuration.metadata import config_field
from app.configuration.models.base import FrozenConfigModel


class ExecutionScalingAddConfig(FrozenConfigModel):
  level_buffer_atr: Decimal = config_field(Decimal('1'),
    item_id='ctrader.env.AUTO_TRADE_ADD_LEVEL_BUFFER_ATR',
    legacy_attr=None,
    env='AUTO_TRADE_ADD_LEVEL_BUFFER_ATR',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_ADD_LEVEL_BUFFER_ATR mapped to execution.scaling.add.level_buffer_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, Decimal('1')),
    ),
    validation_summary='EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )
  min_stop_pips: int = config_field(30,
    item_id='python.settings.auto_trade_add_min_stop_pips',
    legacy_attr='auto_trade_add_min_stop_pips',
    env='AUTO_TRADE_ADD_MIN_STOP_PIPS',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_add_min_stop_pips configuration mapped to execution.scaling.add.min_stop_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 30),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 30),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Int + AutoTradeOptions.Validate',
  )
  pullback_enabled: bool = config_field(False,
    item_id='ctrader.env.AUTO_TRADE_ADD_PULLBACK_ENABLED',
    legacy_attr=None,
    env='AUTO_TRADE_ADD_PULLBACK_ENABLED',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BOOLEAN,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_ADD_PULLBACK_ENABLED mapped to execution.scaling.add.pullback_enabled.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False),
    ),
    validation_summary='EnvironmentResolver.Bool + AutoTradeOptions.Validate',
  )
  pullback_max_retrace: Decimal = config_field(Decimal('0.7'),
    item_id='ctrader.env.AUTO_TRADE_ADD_PULLBACK_MAX_RETRACE',
    legacy_attr=None,
    env='AUTO_TRADE_ADD_PULLBACK_MAX_RETRACE',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.FRACTION,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_ADD_PULLBACK_MAX_RETRACE mapped to execution.scaling.add.pullback_max_retrace.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, Decimal('0.7')),
    ),
    validation_summary='EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )
  pullback_min_retrace: Decimal = config_field(Decimal('0.2'),
    item_id='ctrader.env.AUTO_TRADE_ADD_PULLBACK_MIN_RETRACE',
    legacy_attr=None,
    env='AUTO_TRADE_ADD_PULLBACK_MIN_RETRACE',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.FRACTION,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_ADD_PULLBACK_MIN_RETRACE mapped to execution.scaling.add.pullback_min_retrace.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, Decimal('0.2')),
    ),
    validation_summary='EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )
  size_ratio: float = config_field(0.5,
    item_id='python.settings.auto_trade_add_size_ratio',
    legacy_attr='auto_trade_add_size_ratio',
    env='AUTO_TRADE_ADD_SIZE_RATIO',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.FRACTION,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    description='Legacy auto_trade_add_size_ratio configuration mapped to execution.scaling.add.size_ratio.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 0.5),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )
  stop_buffer_atr: float = config_field(0.3,
    item_id='python.settings.auto_trade_add_stop_buffer_atr',
    legacy_attr='auto_trade_add_stop_buffer_atr',
    env='AUTO_TRADE_ADD_STOP_BUFFER_ATR',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_add_stop_buffer_atr configuration mapped to execution.scaling.add.stop_buffer_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.3),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 0.3),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )


class ExecutionScalingConfig(FrozenConfigModel):
  add: ExecutionScalingAddConfig = Field(default_factory=ExecutionScalingAddConfig)


class ExecutionPolicyConfig(FrozenConfigModel):
  box_min_rr: Decimal = config_field(Decimal('1.25'),
    item_id='ctrader.env.AUTO_TRADE_BOX_MIN_RR',
    legacy_attr=None,
    env='AUTO_TRADE_BOX_MIN_RR',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.MULTIPLIER,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_BOX_MIN_RR mapped to execution.policy.box_min_rr.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, Decimal('1.25')),
    ),
    validation_summary='EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )
  displacement_override_lookback_bars: int = config_field(3,
    item_id='python.settings.auto_trade_displacement_override_lookback_bars',
    legacy_attr='auto_trade_displacement_override_lookback_bars',
    env='AUTO_TRADE_DISPLACEMENT_OVERRIDE_LOOKBACK_BARS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BARS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_displacement_override_lookback_bars configuration mapped to execution.policy.displacement_override_lookback_bars.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  execution_cost_pips: float = config_field(1.0,
    item_id='python.settings.auto_trade_execution_cost_pips',
    legacy_attr='auto_trade_execution_cost_pips',
    env='AUTO_TRADE_EXECUTION_COST_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_execution_cost_pips configuration mapped to execution.policy.execution_cost_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  execution_zone_max_width_atr: float = config_field(2.0,
    item_id='python.settings.auto_trade_execution_zone_max_width_atr',
    legacy_attr='auto_trade_execution_zone_max_width_atr',
    env='AUTO_TRADE_EXECUTION_ZONE_MAX_WIDTH_ATR',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_execution_zone_max_width_atr configuration mapped to execution.policy.execution_zone_max_width_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 2.0),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 2.0),
    ),
    validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
    gt=0,
  )
  execution_zone_max_width_pips: float = config_field(100.0,
    item_id='python.settings.auto_trade_execution_zone_max_width_pips',
    legacy_attr='auto_trade_execution_zone_max_width_pips',
    env='AUTO_TRADE_EXECUTION_ZONE_MAX_WIDTH_PIPS',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_execution_zone_max_width_pips configuration mapped to execution.policy.execution_zone_max_width_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 100.0),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 100),
    ),
    validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
    gt=0,
  )
  flip_exit_buffer_pips: int = config_field(10,
    item_id='ctrader.env.AUTO_TRADE_FLIP_EXIT_BUFFER_PIPS',
    legacy_attr=None,
    env='AUTO_TRADE_FLIP_EXIT_BUFFER_PIPS',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_FLIP_EXIT_BUFFER_PIPS mapped to execution.policy.flip_exit_buffer_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 10),
    ),
    validation_summary='EnvironmentResolver.Int + AutoTradeOptions.Validate',
  )
  group_close_allocation: str = config_field('pro_rata',
    item_id='python.settings.auto_trade_group_close_allocation',
    legacy_attr='auto_trade_group_close_allocation',
    env='AUTO_TRADE_GROUP_CLOSE_ALLOCATION',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.STRING,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_group_close_allocation configuration mapped to execution.policy.group_close_allocation.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 'pro_rata'),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'pro_rata'),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.String + AutoTradeOptions.Validate',
  )
  label: str = config_field('apexvoid-auto',
    item_id='ctrader.env.AUTO_TRADE_LABEL',
    legacy_attr=None,
    env='AUTO_TRADE_LABEL',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.STRING,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_LABEL mapped to execution.policy.label.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'apexvoid-auto'),
    ),
    validation_summary='EnvironmentResolver.String + AutoTradeOptions.Validate',
  )
  max_tranches: int = config_field(2,
    item_id='python.settings.auto_trade_max_tranches',
    legacy_attr='auto_trade_max_tranches',
    env='AUTO_TRADE_MAX_TRANCHES',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.COUNT,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    description='Legacy auto_trade_max_tranches configuration mapped to execution.policy.max_tranches.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 2),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Int + AutoTradeOptions.Validate',
  )
  pip_value_per_lot: Decimal = config_field(Decimal('10'),
    item_id='ctrader.env.AUTO_TRADE_PIP_VALUE_PER_LOT',
    legacy_attr=None,
    env='AUTO_TRADE_PIP_VALUE_PER_LOT',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.MONEY_PER_PIP_PER_LOT,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_PIP_VALUE_PER_LOT mapped to execution.policy.pip_value_per_lot.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, Decimal('10')),
    ),
    validation_summary='EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )
  require_demo_only_token: bool = config_field(False,
    item_id='ctrader.env.AUTO_TRADE_REQUIRE_DEMO_ONLY_TOKEN',
    legacy_attr=None,
    env='AUTO_TRADE_REQUIRE_DEMO_ONLY_TOKEN',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BOOLEAN,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_REQUIRE_DEMO_ONLY_TOKEN mapped to execution.policy.require_demo_only_token.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False),
    ),
    validation_summary='EnvironmentResolver.Bool + AutoTradeOptions.Validate',
  )
  structural_reaction_lookback_bars: int = config_field(3,
    item_id='python.settings.auto_trade_structural_reaction_lookback_bars',
    legacy_attr='auto_trade_structural_reaction_lookback_bars',
    env='AUTO_TRADE_STRUCTURAL_REACTION_LOOKBACK_BARS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BARS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_structural_reaction_lookback_bars configuration mapped to execution.policy.structural_reaction_lookback_bars.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),
    ),
    validation_summary='Pydantic type coercion + Settings cross-field model validator',
    ge=1,
  )


class ExecutionBrokerRecoveryConfig(FrozenConfigModel):
  absence_confirmations: int = config_field(2,
    item_id='ctrader.env.AUTO_TRADE_BROKER_ABSENCE_CONFIRMATIONS',
    legacy_attr=None,
    env='AUTO_TRADE_BROKER_ABSENCE_CONFIRMATIONS',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PRICE,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_BROKER_ABSENCE_CONFIRMATIONS mapped to execution.broker_recovery.absence_confirmations.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 2),
    ),
    validation_summary='EnvironmentResolver.Int + AutoTradeOptions.Validate',
  )


class ExecutionEntryConfig(FrozenConfigModel):
  contract_tolerance_pips: float = config_field(3.0,
    item_id='python.settings.auto_trade_entry_contract_tolerance_pips',
    legacy_attr='auto_trade_entry_contract_tolerance_pips',
    env='AUTO_TRADE_ENTRY_CONTRACT_TOLERANCE_PIPS',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_entry_contract_tolerance_pips configuration mapped to execution.entry.contract_tolerance_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 3.0),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 3),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )
  inside_zone_market_entry_enabled: bool = config_field(True,
    item_id='python.settings.auto_trade_inside_zone_market_entry_enabled',
    legacy_attr='auto_trade_inside_zone_market_entry_enabled',
    env='AUTO_TRADE_INSIDE_ZONE_MARKET_ENTRY_ENABLED',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BOOLEAN,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    description='Legacy auto_trade_inside_zone_market_entry_enabled configuration mapped to execution.entry.inside_zone_market_entry_enabled.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, True),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate',
  )
  max_spread_pips: int = config_field(5,
    item_id='ctrader.env.AUTO_TRADE_MAX_SPREAD_PIPS',
    legacy_attr=None,
    env='AUTO_TRADE_MAX_SPREAD_PIPS',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_MAX_SPREAD_PIPS mapped to execution.entry.max_spread_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 5),
    ),
    validation_summary='EnvironmentResolver.Int + AutoTradeOptions.Validate',
  )
  maximum_chase_distance_pips: float = config_field(40.0,
    item_id='python.settings.auto_trade_max_entry_distance_pips',
    legacy_attr='auto_trade_max_entry_distance_pips',
    env='AUTO_TRADE_MAX_ENTRY_DISTANCE_PIPS',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_max_entry_distance_pips configuration mapped to execution.entry.maximum_chase_distance_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 40.0),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 40),
    ),
    validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.Int + AutoTradeOptions.Validate',
    gt=0,
  )
  poll_ms: int = config_field(1000,
    item_id='ctrader.env.AUTO_TRADE_POLL_MS',
    legacy_attr=None,
    env='AUTO_TRADE_POLL_MS',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.MILLISECONDS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_POLL_MS mapped to execution.entry.poll_ms.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 1000),
    ),
    validation_summary='EnvironmentResolver.Int + AutoTradeOptions.Validate',
  )


class ExecutionTargetingConfig(FrozenConfigModel):
  default_ladder_pips: str = config_field('30,60,90,120,200',
    item_id='python.settings.auto_trade_tp_pips',
    legacy_attr='auto_trade_tp_pips',
    env='AUTO_TRADE_TARGET_PLANS_PIPS',
    aliases=('AUTO_TRADE_TP_PIPS',),
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_tp_pips configuration mapped to execution.targeting.default_ladder_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, '30,60,90,120,200'),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, '30,60,90,120,200'),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.IntList + AutoTradeOptions.Validate',
  )
  post_fill_target_fallback: str = config_field('fill_relative',
    item_id='python.settings.auto_trade_post_fill_target_fallback',
    legacy_attr='auto_trade_post_fill_target_fallback',
    env='AUTO_TRADE_POST_FILL_TARGET_FALLBACK',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.STRING,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    description='Legacy auto_trade_post_fill_target_fallback configuration mapped to execution.targeting.post_fill_target_fallback.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 'fill_relative'),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'fill_relative'),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.String + AutoTradeOptions.Validate',
  )
  range_ladder_pips: str = config_field('15,20,30,40,50,70',
    item_id='python.settings.auto_trade_range_targets_pips',
    legacy_attr='auto_trade_range_targets_pips',
    env='AUTO_TRADE_RANGE_TARGETS_PIPS',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_range_targets_pips configuration mapped to execution.targeting.range_ladder_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, '15,20,30,40,50,70'),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, '15,20,30,40,50,70'),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.IntList + AutoTradeOptions.Validate',
  )
  tp_weights: list[int] = config_field([20, 20, 20, 20, 20],
    item_id='ctrader.env.AUTO_TRADE_TP_WEIGHTS',
    legacy_attr=None,
    env='AUTO_TRADE_TP_WEIGHTS',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.COUNT,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_TP_WEIGHTS mapped to execution.targeting.tp_weights.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, [20, 20, 20, 20, 20]),
    ),
    validation_summary='EnvironmentResolver.IntList + AutoTradeOptions.Validate',
  )
  unfilled_leg_after_tp_policy: str = config_field('cancel',
    item_id='python.settings.auto_trade_unfilled_leg_after_tp_policy',
    legacy_attr='auto_trade_unfilled_leg_after_tp_policy',
    env='AUTO_TRADE_UNFILLED_LEG_AFTER_TP_POLICY',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ENUM,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_unfilled_leg_after_tp_policy configuration mapped to execution.targeting.unfilled_leg_after_tp_policy.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 'cancel'),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'cancel'),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.String + AutoTradeOptions.Validate',
  )


class ExecutionZoneScalingConfig(FrozenConfigModel):
  fill_enabled: bool = config_field(False,
    item_id='python.settings.auto_trade_zone_fill_enabled',
    legacy_attr='auto_trade_zone_fill_enabled',
    env='AUTO_TRADE_ZONE_FILL_ENABLED',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BOOLEAN,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.WARNING,
    description='Legacy auto_trade_zone_fill_enabled configuration mapped to execution.zone_scaling.fill_enabled.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, False),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate',
  )
  fill_fallback_enabled: bool = config_field(True,
    item_id='python.settings.auto_trade_zone_fill_fallback_enabled',
    legacy_attr='auto_trade_zone_fill_fallback_enabled',
    env='AUTO_TRADE_ZONE_FILL_FALLBACK_ENABLED',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BOOLEAN,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    description='Legacy auto_trade_zone_fill_fallback_enabled configuration mapped to execution.zone_scaling.fill_fallback_enabled.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, True),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate',
  )
  fill_min_atr: float = config_field(0.5,
    item_id='python.settings.auto_trade_zone_fill_min_atr',
    legacy_attr='auto_trade_zone_fill_min_atr',
    env='AUTO_TRADE_ZONE_FILL_MIN_ATR',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    description='Legacy auto_trade_zone_fill_min_atr configuration mapped to execution.zone_scaling.fill_min_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 0.5),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )
  fill_min_lots: Decimal = config_field(Decimal('0.09'),
    item_id='ctrader.env.AUTO_TRADE_ZONE_FILL_MIN_LOTS',
    legacy_attr=None,
    env='AUTO_TRADE_ZONE_FILL_MIN_LOTS',
    owner=ConfigOwner.CTRADER,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.LOTS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='cTrader runtime option AUTO_TRADE_ZONE_FILL_MIN_LOTS mapped to execution.zone_scaling.fill_min_lots.',
    default_contexts=(
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, Decimal('0.09')),
    ),
    validation_summary='EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )
  first_leg_fraction: float = config_field(0.7,
    item_id='python.settings.auto_trade_zone_scale_first_leg_fraction',
    legacy_attr='auto_trade_zone_scale_first_leg_fraction',
    env='AUTO_TRADE_ZONE_SCALE_FIRST_LEG_FRACTION',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.FRACTION,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_zone_scale_first_leg_fraction configuration mapped to execution.zone_scaling.first_leg_fraction.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.7),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  scale_step_atr: float = config_field(0.5,
    item_id='python.settings.auto_trade_zone_scale_step_atr',
    legacy_attr='auto_trade_zone_scale_step_atr',
    env='AUTO_TRADE_ZONE_SCALE_STEP_ATR',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_zone_scale_step_atr configuration mapped to execution.zone_scaling.scale_step_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  scale_undersized_policy: str = config_field('single_entry',
    item_id='python.settings.auto_trade_zone_scale_undersized_policy',
    legacy_attr='auto_trade_zone_scale_undersized_policy',
    env='AUTO_TRADE_ZONE_SCALE_UNDERSIZED_POLICY',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ENUM,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_zone_scale_undersized_policy configuration mapped to execution.zone_scaling.scale_undersized_policy.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 'single_entry'),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'single_entry'),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.String + AutoTradeOptions.Validate',
  )


class ExecutionStopsReactionConfig(FrozenConfigModel):
  room_floor_pips: int = config_field(20,
    item_id='python.settings.auto_trade_reaction_room_stop_floor_pips',
    legacy_attr='auto_trade_reaction_room_stop_floor_pips',
    env='AUTO_TRADE_REACTION_ROOM_STOP_FLOOR_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_reaction_room_stop_floor_pips configuration mapped to execution.stops.reaction.room_floor_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 20),
    ),
    validation_summary='Pydantic required/type coercion only',
  )


class ExecutionStopsTrendConfig(FrozenConfigModel):
  minimum_pips: int = config_field(40,
    item_id='python.settings.auto_trade_trend_stop_min_pips',
    legacy_attr='auto_trade_trend_stop_min_pips',
    env='AUTO_TRADE_TREND_STOP_MIN_PIPS',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_trend_stop_min_pips configuration mapped to execution.stops.trend.minimum_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 40),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 40),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Int + AutoTradeOptions.Validate',
  )


class ExecutionStopsConfig(FrozenConfigModel):
  be_buffer_ticks: int = config_field(6,
    item_id='python.settings.auto_trade_be_buffer_ticks',
    legacy_attr='auto_trade_be_buffer_ticks',
    env='AUTO_TRADE_BE_BUFFER_TICKS',
    aliases=('AUTO_TRADE_BE_BUFFER_PIPS',),
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.TICKS,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_be_buffer_ticks configuration mapped to execution.stops.be_buffer_ticks.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 6),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 6),
    ),
    validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.Int + AutoTradeOptions.Validate',
    ge=0,
    lt=1000,
  )
  reaction: ExecutionStopsReactionConfig = Field(default_factory=ExecutionStopsReactionConfig)
  sl_distance: float = config_field(6.5,
    item_id='python.settings.auto_trade_sl_distance',
    legacy_attr='auto_trade_sl_distance',
    env='AUTO_TRADE_SL_DISTANCE',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PRICE,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_sl_distance configuration mapped to execution.stops.sl_distance.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 6.5),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 6.5),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )
  stop_push_beyond_zone: bool = config_field(True,
    item_id='python.settings.auto_trade_stop_push_beyond_zone',
    legacy_attr='auto_trade_stop_push_beyond_zone',
    env='AUTO_TRADE_STOP_PUSH_BEYOND_ZONE',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BOOLEAN,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    description='Legacy auto_trade_stop_push_beyond_zone configuration mapped to execution.stops.stop_push_beyond_zone.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, True),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate',
  )
  trend: ExecutionStopsTrendConfig = Field(default_factory=ExecutionStopsTrendConfig)
  wick_stop_buffer_atr: float = config_field(0.15,
    item_id='python.settings.auto_trade_wick_stop_buffer_atr',
    legacy_attr='auto_trade_wick_stop_buffer_atr',
    env='AUTO_TRADE_WICK_STOP_BUFFER_ATR',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_wick_stop_buffer_atr configuration mapped to execution.stops.wick_stop_buffer_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.15),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 0.15),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )


class ExecutionMappedZoneConfig(FrozenConfigModel):
  counter_bias_min_score: float = config_field(6.0,
    item_id='python.settings.auto_trade_map_counter_bias_min_score',
    legacy_attr='auto_trade_map_counter_bias_min_score',
    env='AUTO_TRADE_MAP_COUNTER_BIAS_MIN_SCORE',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.SCORE,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_map_counter_bias_min_score configuration mapped to execution.mapped_zone.counter_bias_min_score.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 6.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  execute_distance_atr: float = config_field(1.5,
    item_id='python.settings.auto_trade_map_execute_distance_atr',
    legacy_attr='auto_trade_map_execute_distance_atr',
    env='AUTO_TRADE_MAP_EXECUTE_DISTANCE_ATR',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_map_execute_distance_atr configuration mapped to execution.mapped_zone.execute_distance_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.5),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  execute_tolerance_atr: float = config_field(0.15,
    item_id='python.settings.auto_trade_map_execute_tolerance_atr',
    legacy_attr='auto_trade_map_execute_tolerance_atr',
    env='AUTO_TRADE_MAP_EXECUTE_TOLERANCE_ATR',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_map_execute_tolerance_atr configuration mapped to execution.mapped_zone.execute_tolerance_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.15),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  execute_tolerance_pips: float = config_field(3.0,
    item_id='python.settings.auto_trade_map_execute_tolerance_pips',
    legacy_attr='auto_trade_map_execute_tolerance_pips',
    env='AUTO_TRADE_MAP_EXECUTE_TOLERANCE_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_map_execute_tolerance_pips configuration mapped to execution.mapped_zone.execute_tolerance_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 3.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  hard_entry_drift_pips: float = config_field(20.0,
    item_id='python.settings.auto_trade_map_hard_entry_drift_pips',
    legacy_attr='auto_trade_map_hard_entry_drift_pips',
    env='AUTO_TRADE_MAP_HARD_ENTRY_DRIFT_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_map_hard_entry_drift_pips configuration mapped to execution.mapped_zone.hard_entry_drift_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 20.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  max_entry_drift_atr: float = config_field(0.4,
    item_id='python.settings.auto_trade_map_max_entry_drift_atr',
    legacy_attr='auto_trade_map_max_entry_drift_atr',
    env='AUTO_TRADE_MAP_MAX_ENTRY_DRIFT_ATR',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_map_max_entry_drift_atr configuration mapped to execution.mapped_zone.max_entry_drift_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.4),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  min_entry_drift_pips: float = config_field(10.0,
    item_id='python.settings.auto_trade_map_min_entry_drift_pips',
    legacy_attr='auto_trade_map_min_entry_drift_pips',
    env='AUTO_TRADE_MAP_MIN_ENTRY_DRIFT_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_map_min_entry_drift_pips configuration mapped to execution.mapped_zone.min_entry_drift_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 10.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  reaction_lookback_bars: int = config_field(5,
    item_id='python.settings.auto_trade_map_reaction_lookback_bars',
    legacy_attr='auto_trade_map_reaction_lookback_bars',
    env='AUTO_TRADE_MAP_REACTION_LOOKBACK_BARS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BARS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_map_reaction_lookback_bars configuration mapped to execution.mapped_zone.reaction_lookback_bars.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 5),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  thesis_lock_enabled: bool = config_field(True,
    item_id='python.settings.auto_trade_map_thesis_lock_enabled',
    legacy_attr='auto_trade_map_thesis_lock_enabled',
    env='AUTO_TRADE_MAP_THESIS_LOCK_ENABLED',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BOOLEAN,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.WARNING,
    description='Legacy auto_trade_map_thesis_lock_enabled configuration mapped to execution.mapped_zone.thesis_lock_enabled.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, True),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate',
  )
  track_distance_atr: float = config_field(8.0,
    item_id='python.settings.auto_trade_map_track_distance_atr',
    legacy_attr='auto_trade_map_track_distance_atr',
    env='AUTO_TRADE_MAP_TRACK_DISTANCE_ATR',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_map_track_distance_atr configuration mapped to execution.mapped_zone.track_distance_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 8.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  zone_min_width_abs: float = config_field(1.0,
    item_id='python.settings.auto_trade_map_zone_min_width_abs',
    legacy_attr='auto_trade_map_zone_min_width_abs',
    env='AUTO_TRADE_MAP_ZONE_MIN_WIDTH_ABS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PRICE,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_map_zone_min_width_abs configuration mapped to execution.mapped_zone.zone_min_width_abs.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  zone_min_width_atr: float = config_field(0.15,
    item_id='python.settings.auto_trade_map_zone_min_width_atr',
    legacy_attr='auto_trade_map_zone_min_width_atr',
    env='AUTO_TRADE_MAP_ZONE_MIN_WIDTH_ATR',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_map_zone_min_width_atr configuration mapped to execution.mapped_zone.zone_min_width_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.15),
    ),
    validation_summary='Pydantic required/type coercion only',
  )


class ExecutionRangeConfig(FrozenConfigModel):
  box_move_sl_to_be_after_scale_out: bool = config_field(False,
    item_id='python.settings.auto_trade_range_box_move_sl_to_be_after_scale_out',
    legacy_attr='auto_trade_range_box_move_sl_to_be_after_scale_out',
    env='AUTO_TRADE_RANGE_BOX_MOVE_SL_TO_BE_AFTER_SCALE_OUT',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BOOLEAN,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.WARNING,
    description='Legacy auto_trade_range_box_move_sl_to_be_after_scale_out configuration mapped to execution.range.box_move_sl_to_be_after_scale_out.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, False),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate',
  )
  box_scale_out_fraction: float = config_field(0.5,
    item_id='python.settings.auto_trade_range_box_scale_out_fraction',
    legacy_attr='auto_trade_range_box_scale_out_fraction',
    env='AUTO_TRADE_RANGE_BOX_SCALE_OUT_FRACTION',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.FRACTION,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.WARNING,
    description='Legacy auto_trade_range_box_scale_out_fraction configuration mapped to execution.range.box_scale_out_fraction.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 0.5),
    ),
    validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
    gt=0,
    lt=1,
  )
  box_scale_out_threshold_pips: int = config_field(70,
    item_id='python.settings.auto_trade_range_box_scale_out_threshold_pips',
    legacy_attr='auto_trade_range_box_scale_out_threshold_pips',
    env='AUTO_TRADE_RANGE_BOX_SCALE_OUT_THRESHOLD_PIPS',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.WARNING,
    description='Legacy auto_trade_range_box_scale_out_threshold_pips configuration mapped to execution.range.box_scale_out_threshold_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 70),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 70),
    ),
    validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.Int + AutoTradeOptions.Validate',
    gt=0,
  )
  box_scale_out_trigger_pips: int = config_field(30,
    item_id='python.settings.auto_trade_range_box_scale_out_trigger_pips',
    legacy_attr='auto_trade_range_box_scale_out_trigger_pips',
    env='AUTO_TRADE_RANGE_BOX_SCALE_OUT_TRIGGER_PIPS',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.WARNING,
    description='Legacy auto_trade_range_box_scale_out_trigger_pips configuration mapped to execution.range.box_scale_out_trigger_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 30),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 30),
    ),
    validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.Int + AutoTradeOptions.Validate',
    gt=0,
  )
  hard_entry_drift_pips: float = config_field(20.0,
    item_id='python.settings.auto_trade_range_hard_entry_drift_pips',
    legacy_attr='auto_trade_range_hard_entry_drift_pips',
    env='AUTO_TRADE_RANGE_HARD_ENTRY_DRIFT_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_range_hard_entry_drift_pips configuration mapped to execution.range.hard_entry_drift_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 20.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  max_entry_drift_atr: float = config_field(0.35,
    item_id='python.settings.auto_trade_range_max_entry_drift_atr',
    legacy_attr='auto_trade_range_max_entry_drift_atr',
    env='AUTO_TRADE_RANGE_MAX_ENTRY_DRIFT_ATR',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_range_max_entry_drift_atr configuration mapped to execution.range.max_entry_drift_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.35),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  min_entry_drift_pips: float = config_field(10.0,
    item_id='python.settings.auto_trade_range_min_entry_drift_pips',
    legacy_attr='auto_trade_range_min_entry_drift_pips',
    env='AUTO_TRADE_RANGE_MIN_ENTRY_DRIFT_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_range_min_entry_drift_pips configuration mapped to execution.range.min_entry_drift_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 10.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  min_rr: float = config_field(1.0,
    item_id='python.settings.auto_trade_range_min_rr',
    legacy_attr='auto_trade_range_min_rr',
    env='AUTO_TRADE_RANGE_MIN_RR',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.MULTIPLIER,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_range_min_rr configuration mapped to execution.range.min_rr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  min_target_pips: float = config_field(15.0,
    item_id='python.settings.auto_trade_range_min_target_pips',
    legacy_attr='auto_trade_range_min_target_pips',
    env='AUTO_TRADE_RANGE_MIN_TARGET_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_range_min_target_pips configuration mapped to execution.range.min_target_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 15.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  room_stop_floor_pips: int = config_field(15,
    item_id='python.settings.auto_trade_range_room_stop_floor_pips',
    legacy_attr='auto_trade_range_room_stop_floor_pips',
    env='AUTO_TRADE_RANGE_ROOM_STOP_FLOOR_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_range_room_stop_floor_pips configuration mapped to execution.range.room_stop_floor_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 15),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  tp_buffer_pips: float = config_field(3.0,
    item_id='python.settings.auto_trade_range_tp_buffer_pips',
    legacy_attr='auto_trade_range_tp_buffer_pips',
    env='AUTO_TRADE_RANGE_TP_BUFFER_PIPS',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_range_tp_buffer_pips configuration mapped to execution.range.tp_buffer_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 3.0),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 3),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )

  @model_validator(mode="after")
  def validate_box_scale_out(self):
    if self.box_scale_out_trigger_pips >= self.box_scale_out_threshold_pips:
      raise ValueError(
        "range box scale-out trigger must be below its threshold"
      )
    return self


class ExecutionReactionConfig(FrozenConfigModel):
  market_fraction: float = config_field(0.7,
    item_id='python.settings.auto_trade_reaction_market_fraction',
    legacy_attr='auto_trade_reaction_market_fraction',
    env='AUTO_TRADE_REACTION_MARKET_FRACTION',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.FRACTION,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    description='Legacy auto_trade_reaction_market_fraction configuration mapped to execution.reaction.market_fraction.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.7),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 0.7),
    ),
    validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
    gt=0,
  )
  room_stop_min_rr: float = config_field(1.0,
    item_id='python.settings.auto_trade_reaction_room_stop_min_rr',
    legacy_attr='auto_trade_reaction_room_stop_min_rr',
    env='AUTO_TRADE_REACTION_ROOM_STOP_MIN_RR',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.MULTIPLIER,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_reaction_room_stop_min_rr configuration mapped to execution.reaction.room_stop_min_rr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  scale_fraction: float = config_field(0.3,
    item_id='python.settings.auto_trade_reaction_scale_fraction',
    legacy_attr='auto_trade_reaction_scale_fraction',
    env='AUTO_TRADE_REACTION_SCALE_FRACTION',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.FRACTION,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    description='Legacy auto_trade_reaction_scale_fraction configuration mapped to execution.reaction.scale_fraction.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.3),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 0.3),
    ),
    validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
    gt=0,
  )
  scale_invalid_policy: str = config_field('single_market',
    item_id='python.settings.auto_trade_reaction_scale_invalid_policy',
    legacy_attr='auto_trade_reaction_scale_invalid_policy',
    env='AUTO_TRADE_REACTION_SCALE_INVALID_POLICY',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ENUM,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    description='Legacy auto_trade_reaction_scale_invalid_policy configuration mapped to execution.reaction.scale_invalid_policy.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 'single_market'),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'single_market'),
    ),
    allowed_values=('single_market', 'reject'),
    validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.String + AutoTradeOptions.Validate',
    pattern='^(single_market|reject)$',
  )
  scale_step_atr: float = config_field(0.5,
    item_id='python.settings.auto_trade_reaction_scale_step_atr',
    legacy_attr='auto_trade_reaction_scale_step_atr',
    env='AUTO_TRADE_REACTION_SCALE_STEP_ATR',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    description='Legacy auto_trade_reaction_scale_step_atr configuration mapped to execution.reaction.scale_step_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 0.5),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Decimal + AutoTradeOptions.Validate',
  )
  stop_max_pips: int = config_field(60,
    item_id='python.settings.auto_trade_reaction_stop_max_pips',
    legacy_attr='auto_trade_reaction_stop_max_pips',
    env='AUTO_TRADE_REACTION_STOP_MAX_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_reaction_stop_max_pips configuration mapped to execution.reaction.stop_max_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 60),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  stop_min_pips: int = config_field(40,
    item_id='python.settings.auto_trade_reaction_stop_min_pips',
    legacy_attr='auto_trade_reaction_stop_min_pips',
    env='AUTO_TRADE_REACTION_STOP_MIN_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_reaction_stop_min_pips configuration mapped to execution.reaction.stop_min_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 40),
    ),
    validation_summary='Pydantic required/type coercion only',
  )

  @field_validator("scale_invalid_policy", mode="before")
  @classmethod
  def normalize_scale_invalid_policy(cls, value):
    return value.strip().lower() if isinstance(value, str) else value

  @model_validator(mode="after")
  def validate_scale_fractions(self):
    if abs(self.market_fraction + self.scale_fraction - 1.0) > 1e-6:
      raise ValueError(
        "reaction market and scale fractions must sum to 1.0"
      )
    return self


class ExecutionRegimeConfig(FrozenConfigModel):
  direction_enabled: bool = config_field(False,
    item_id='python.settings.auto_trade_regime_direction_enabled',
    legacy_attr='auto_trade_regime_direction_enabled',
    env='AUTO_TRADE_REGIME_DIRECTION_ENABLED',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BOOLEAN,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_regime_direction_enabled configuration mapped to execution.regime.direction_enabled.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, False),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  direction_lookback: int = config_field(120,
    item_id='python.settings.auto_trade_regime_direction_lookback',
    legacy_attr='auto_trade_regime_direction_lookback',
    env='AUTO_TRADE_REGIME_DIRECTION_LOOKBACK',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.BARS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_regime_direction_lookback configuration mapped to execution.regime.direction_lookback.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 120),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  min_directional_swings: int = config_field(3,
    item_id='python.settings.auto_trade_regime_min_directional_swings',
    legacy_attr='auto_trade_regime_min_directional_swings',
    env='AUTO_TRADE_REGIME_MIN_DIRECTIONAL_SWINGS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.COUNT,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_regime_min_directional_swings configuration mapped to execution.regime.min_directional_swings.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  min_displacement_atr: float = config_field(4.0,
    item_id='python.settings.auto_trade_regime_min_displacement_atr',
    legacy_attr='auto_trade_regime_min_displacement_atr',
    env='AUTO_TRADE_REGIME_MIN_DISPLACEMENT_ATR',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_regime_min_displacement_atr configuration mapped to execution.regime.min_displacement_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 4.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )


class ExecutionTrendConfig(FrozenConfigModel):
  hard_entry_drift_pips: float = config_field(30.0,
    item_id='python.settings.auto_trade_trend_hard_entry_drift_pips',
    legacy_attr='auto_trade_trend_hard_entry_drift_pips',
    env='AUTO_TRADE_TREND_HARD_ENTRY_DRIFT_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_trend_hard_entry_drift_pips configuration mapped to execution.trend.hard_entry_drift_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 30.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  max_entry_drift_atr: float = config_field(0.85,
    item_id='python.settings.auto_trade_trend_max_entry_drift_atr',
    legacy_attr='auto_trade_trend_max_entry_drift_atr',
    env='AUTO_TRADE_TREND_MAX_ENTRY_DRIFT_ATR',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.ATR,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_trend_max_entry_drift_atr configuration mapped to execution.trend.max_entry_drift_atr.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.85),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  min_entry_drift_pips: float = config_field(15.0,
    item_id='python.settings.auto_trade_trend_min_entry_drift_pips',
    legacy_attr='auto_trade_trend_min_entry_drift_pips',
    env='AUTO_TRADE_TREND_MIN_ENTRY_DRIFT_PIPS',
    owner=ConfigOwner.PYTHON,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    description='Legacy auto_trade_trend_min_entry_drift_pips configuration mapped to execution.trend.min_entry_drift_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 15.0),
    ),
    validation_summary='Pydantic required/type coercion only',
  )
  stop_max_pips: int = config_field(60,
    item_id='python.settings.auto_trade_trend_stop_max_pips',
    legacy_attr='auto_trade_trend_stop_max_pips',
    env='AUTO_TRADE_TREND_STOP_MAX_PIPS',
    owner=ConfigOwner.SHARED,
    reload=ReloadPolicy.NEW_SETUP_ONLY,
    runtime_reload=ReloadPolicy.RESTART,
    unit=ConfigUnit.PIPS,
    risk=RiskClassification.EXECUTION_SAFETY,
    shared_with_ctrader=True,
    mismatch_policy=MismatchPolicy.FATAL,
    description='Legacy auto_trade_trend_stop_max_pips configuration mapped to execution.trend.stop_max_pips.',
    default_contexts=(
      ContextDefault(DefaultContext.PYTHON_SCHEMA, 60),
      ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 60),
    ),
    validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Int + AutoTradeOptions.Validate',
  )


class ExecutionConfig(FrozenConfigModel):
  broker_recovery: ExecutionBrokerRecoveryConfig = Field(default_factory=ExecutionBrokerRecoveryConfig)
  entry: ExecutionEntryConfig = Field(default_factory=ExecutionEntryConfig)
  mapped_zone: ExecutionMappedZoneConfig = Field(default_factory=ExecutionMappedZoneConfig)
  policy: ExecutionPolicyConfig = Field(default_factory=ExecutionPolicyConfig)
  range: ExecutionRangeConfig = Field(default_factory=ExecutionRangeConfig)
  reaction: ExecutionReactionConfig = Field(default_factory=ExecutionReactionConfig)
  regime: ExecutionRegimeConfig = Field(default_factory=ExecutionRegimeConfig)
  scaling: ExecutionScalingConfig = Field(default_factory=ExecutionScalingConfig)
  stops: ExecutionStopsConfig = Field(default_factory=ExecutionStopsConfig)
  targeting: ExecutionTargetingConfig = Field(default_factory=ExecutionTargetingConfig)
  trend: ExecutionTrendConfig = Field(default_factory=ExecutionTrendConfig)
  zone_scaling: ExecutionZoneScalingConfig = Field(default_factory=ExecutionZoneScalingConfig)
