"""Complete Canonical Catalog V2 configuration domain. """
from pydantic import Field
from app.configuration.metadata import ConfigKind
from app.configuration.metadata import ConfigOwner
from app.configuration.metadata import ConfigUnit
from app.configuration.metadata import ContextDefault
from app.configuration.metadata import DefaultContext
from app.configuration.metadata import MismatchPolicy
from app.configuration.metadata import ReloadPolicy
from app.configuration.metadata import RiskClassification
from app.configuration.metadata import config_field
from app.configuration.models.base import FrozenConfigModel

class MarketDataCtraderFeedConfig(FrozenConfigModel):
    backfill_bars: int = config_field(1500, canonical_env='CTRADER_BACKFILL_BARS', owner=ConfigOwner.CTRADER, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.INFRASTRUCTURE, description='cTrader configuration option CTRADER_BACKFILL_BARS controlling  (bars).', default_contexts=(ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 1500),), validation_summary='FeedOptions.Env')
    bar_quality_lookback_bars: int = config_field(6, canonical_env='BAR_QUALITY_LOOKBACK', owner=ConfigOwner.CTRADER, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.INFRASTRUCTURE, description='cTrader configuration option BAR_QUALITY_LOOKBACK controlling  (bars).', default_contexts=(ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 6),), validation_summary='FeedOptions.Env')
    bars_channel: str = config_field('bars:new', canonical_env='BARS_CHANNEL', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.STRING, risk=RiskClassification.INFRASTRUCTURE, shared_with_ctrader=True, description='Controls .', default_contexts=(ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'bars:new'),), validation_summary='FeedOptions.Env', evidence_notes=('Feed option is configurable while the Python bars consumer contract is not a legacy Settings field.',))
    bars_window_max: int = config_field(1500, canonical_env='BARS_WINDOW_MAX', owner=ConfigOwner.CTRADER, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.INFRASTRUCTURE, description='cTrader configuration option BARS_WINDOW_MAX controlling  (bars).', default_contexts=(ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 1500),), validation_summary='FeedOptions.Env')
    health_file: str = config_field('/tmp/ctrader-feed.heartbeat', canonical_env='HEALTH_FILE', owner=ConfigOwner.CTRADER, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PATH, risk=RiskClassification.INFRASTRUCTURE, description='cTrader configuration option HEALTH_FILE controlling .', default_contexts=(ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, '/tmp/ctrader-feed.heartbeat'),), validation_summary='FeedOptions.Env')
    symbol: str = config_field('XAUUSD', canonical_env='CTRADER_SYMBOL', owner=ConfigOwner.CTRADER, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.INFRASTRUCTURE, description='cTrader configuration option CTRADER_SYMBOL controlling .', default_contexts=(ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 'XAUUSD'),), validation_summary='FeedOptions.Env')
    timeframes: list[str] = config_field(['M1', 'M5', 'M15', 'H1'], canonical_env='CTRADER_TIMEFRAMES', owner=ConfigOwner.CTRADER, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.INFRASTRUCTURE, description='cTrader configuration option CTRADER_TIMEFRAMES controlling .', default_contexts=(ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, ['M1', 'M5', 'M15', 'H1']),), validation_summary='FeedOptions.Env', evidence_notes=('C# schema defaults M1,M5,M15,H1; deployment profile values remain separate evidence.',))

class MarketDataSpotConfig(FrozenConfigModel):
    fresh_secs: int = config_field(30, canonical_env='SPOT_FRESH_SECS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SECONDS, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (seconds).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 30),), validation_summary='Pydantic required/type coercion only')
    max_deviation_pct: float = config_field(2.0, canonical_env='SPOT_MAX_DEVIATION_PCT', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PERCENT, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (percent).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2.0),), validation_summary='Pydantic required/type coercion only')
    maximum_age_seconds: int = config_field(5, canonical_env='AUTO_TRADE_SPOT_MAX_AGE_SECONDS', deprecated_env_aliases=('AUTO_TRADE_SPOT_MAX_AGE',), owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEXT_WORKER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SECONDS, risk=RiskClassification.LIFECYCLE, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.FATAL, description='Controls  (seconds).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, 5)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Int + AutoTradeOptions.Validate')

class MarketDataCalendarConfig(FrozenConfigModel):
    currencies: str = config_field('USD', canonical_env='CALENDAR_CURRENCIES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.STRING, risk=RiskClassification.INFRASTRUCTURE, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'USD'),), validation_summary='Pydantic required/type coercion only')
    enabled: bool = config_field(True, canonical_env='CALENDAR_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.INFRASTRUCTURE, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    event_guard_hours: float = config_field(4.0, canonical_env='EVENT_GUARD_HOURS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.HOURS, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (hours).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 4.0),), validation_summary='Pydantic required/type coercion only')
    feed_nextweek: str = config_field('https://nfs.faireconomy.media/ff_calendar_nextweek.json', canonical_env='CALENDAR_FEED_NEXTWEEK', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.URL, risk=RiskClassification.INFRASTRUCTURE, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'https://nfs.faireconomy.media/ff_calendar_nextweek.json'),), validation_summary='Pydantic required/type coercion only')
    feed_thisweek: str = config_field('https://nfs.faireconomy.media/ff_calendar_thisweek.json', canonical_env='CALENDAR_FEED_THISWEEK', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.URL, risk=RiskClassification.INFRASTRUCTURE, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'https://nfs.faireconomy.media/ff_calendar_thisweek.json'),), validation_summary='Pydantic required/type coercion only')
    news_brief_hour: int = config_field(7, canonical_env='NEWS_BRIEF_HOUR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.UTC_HOUR, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (utc_hour).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 7),), validation_summary='Pydantic required/type coercion only')
    news_guard_block: bool = config_field(False, canonical_env='NEWS_GUARD_BLOCK', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.INFRASTRUCTURE, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    oil_keywords: str = config_field('crude oil inventories,opec,cushing,api weekly crude', canonical_env='OIL_KEYWORDS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.INFRASTRUCTURE, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'crude oil inventories,opec,cushing,api weekly crude'),), validation_summary='Pydantic required/type coercion only')
    user_agent: str = config_field('apexvoid-trading-bot/1.0 (+contact)', canonical_env='CALENDAR_USER_AGENT', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.STRING, risk=RiskClassification.INFRASTRUCTURE, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'apexvoid-trading-bot/1.0 (+contact)'),), validation_summary='Pydantic required/type coercion only')

class MarketDataSessionsConfig(FrozenConfigModel):
    asia_start: int = config_field(22, canonical_env='SESSION_ASIA_START', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.UTC_HOUR, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (utc_hour).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 22),), validation_summary='Pydantic required/type coercion only')
    daily_rollover_utc_hour: int = config_field(21, canonical_env='DAILY_ROLLOVER_UTC_HOUR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.UTC_HOUR, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (utc_hour).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 21),), validation_summary='Pydantic required/type coercion only')
    london_start: int = config_field(7, canonical_env='SESSION_LONDON_START', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.UTC_HOUR, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (utc_hour).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 7),), validation_summary='Pydantic required/type coercion only')
    ny_start: int = config_field(13, canonical_env='SESSION_NY_START', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.UTC_HOUR, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (utc_hour).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 13),), validation_summary='Pydantic required/type coercion only')

class MarketDataScannerConfig(FrozenConfigModel):
    alert_ttl: int = config_field(7200, canonical_env='SCANNER_ALERT_TTL', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SECONDS, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (seconds).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 7200),), validation_summary='Pydantic required/type coercion only')
    confluence_floor: int = config_field(2, canonical_env='SCANNER_CONFLUENCE_FLOOR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    execution_timeframe: str = config_field('M5', canonical_env='SCANNER_EXEC_TF', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.INFRASTRUCTURE, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'M5'),), validation_summary='Pydantic required/type coercion only')
    htf: str = config_field('H1,M15', canonical_env='SCANNER_HTF', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.STRING, risk=RiskClassification.INFRASTRUCTURE, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'H1,M15'),), validation_summary='Pydantic required/type coercion only')
    level_bucket_pips: int = config_field(20, canonical_env='SCANNER_LEVEL_BUCKET', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (pips).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 20),), validation_summary='Pydantic required/type coercion only')
    symbols: str = config_field('XAU', canonical_env='SCANNER_SYMBOLS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.INFRASTRUCTURE, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'XAU'),), validation_summary='Pydantic required/type coercion only')
    window: int = config_field(500, canonical_env='SCANNER_WINDOW', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 500),), validation_summary='Pydantic required/type coercion only')

class MarketDataTiingoConfig(FrozenConfigModel):
    api_key: str | None = config_field(None, canonical_env='TIINGO_API_KEY', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.IDENTIFIER, risk=RiskClassification.BROKER_ACCOUNT_SAFETY, secret=True, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, '<redacted>'),), validation_summary='Pydantic required/type coercion only')

class MarketDataWatcherConfig(FrozenConfigModel):
    ctrader_stale_seconds: int = config_field(180, canonical_env='WATCHER_CTRADER_STALE_SECONDS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SECONDS, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (seconds).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 180),), validation_summary='Pydantic required/type coercion only')
    interval_seconds: int = config_field(30, canonical_env='TRACK_INTERVAL', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SECONDS, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (seconds).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 30),), validation_summary='Pydantic required/type coercion only')

class MarketDataLookbacksConfig(FrozenConfigModel):
    h1_bars: int = config_field(400, canonical_env='XAU_LOOKBACK_H1_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.INFRASTRUCTURE, description='H1 closed-bar lookback for major structure (weekly/daily range, untested swing H/L, flip zones). Target window ~2.5-4 weeks (300-500 bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 400),), validation_summary='Pydantic required/type coercion only', ge=50)
    m15_bars: int = config_field(250, canonical_env='XAU_LOOKBACK_M15_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.INFRASTRUCTURE, description='M15 closed-bar lookback for session structure (Asia/London/NY range, intermediate OB). Target window ~2-3 days (200-300 bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 250),), validation_summary='Pydantic required/type coercion only', ge=50)
    m1_bars: int = config_field(150, canonical_env='XAU_LOOKBACK_M1_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.INFRASTRUCTURE, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 150),), validation_summary='Pydantic required/type coercion only', ge=50)
    m5_bars: int = config_field(150, canonical_env='XAU_LOOKBACK_M5_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEXT_SCANNER_CYCLE, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.INFRASTRUCTURE, description='M5 closed-bar lookback for entry structure (OB/FVG/micro BOS/retest). Target window is current + previous session (100-150 bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 150),), validation_summary='Pydantic required/type coercion only', ge=50)

class MarketDataConfig(FrozenConfigModel):
    calendar: MarketDataCalendarConfig = Field(default_factory=MarketDataCalendarConfig)
    ctrader_feed: MarketDataCtraderFeedConfig = Field(default_factory=MarketDataCtraderFeedConfig)
    lookbacks: MarketDataLookbacksConfig = Field(default_factory=MarketDataLookbacksConfig)
    scanner: MarketDataScannerConfig = Field(default_factory=MarketDataScannerConfig)
    sessions: MarketDataSessionsConfig = Field(default_factory=MarketDataSessionsConfig)
    spot: MarketDataSpotConfig = Field(default_factory=MarketDataSpotConfig)
    tiingo: MarketDataTiingoConfig = Field(default_factory=MarketDataTiingoConfig)
    watcher: MarketDataWatcherConfig = Field(default_factory=MarketDataWatcherConfig)
