"""Complete Canonical Catalog V2 configuration domain. """
from pydantic import Field
from pydantic import field_validator
from app.configuration.metadata import ConfigKind
from app.configuration.metadata import ConfigOwner
from app.configuration.metadata import ConfigUnit
from app.configuration.metadata import ContextDefault
from app.configuration.metadata import DefaultContext
from app.configuration.metadata import MismatchPolicy
from app.configuration.metadata import ReloadPolicy
from app.configuration.metadata import RiskClassification
from app.configuration.metadata import config_field
from app.configuration.models.base import FrozenConfigModel

class StrategiesAutoScalpBoxConfig(FrozenConfigModel):
    break_buffer_atr: float = config_field(0.12, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.break_buffer_atr.', validation_summary='none; source constant')
    break_confirmation_closes: int = config_field(2, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.break_confirmation_closes.', validation_summary='none; source constant')
    lookback_bars: int = config_field(60, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.lookback_bars.', validation_summary='none; source constant')
    maximum_close_efficiency: float = config_field(0.45, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.maximum_close_efficiency.', validation_summary='none; source constant')
    maximum_touch_band_pips: int = config_field(6, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.PIPS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.maximum_touch_band_pips.', validation_summary='none; source constant')
    maximum_width_pips: int = config_field(120, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.PIPS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.maximum_width_pips.', validation_summary='none; source constant')
    minimum_body_fraction: float = config_field(0.15, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.minimum_body_fraction.', validation_summary='none; source constant')
    minimum_inside_ratio: float = config_field(0.82, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.minimum_inside_ratio.', validation_summary='none; source constant')
    minimum_touch_band_pips: float = config_field(2.5, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.PIPS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.minimum_touch_band_pips.', validation_summary='none; source constant')
    minimum_touch_episodes: int = config_field(2, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.minimum_touch_episodes.', validation_summary='none; source constant')
    minimum_wick_fraction: float = config_field(0.15, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.minimum_wick_fraction.', validation_summary='none; source constant')
    minimum_width_pips: int = config_field(55, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.PIPS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.minimum_width_pips.', validation_summary='none; source constant')
    recovery_atr: float = config_field(0.15, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.recovery_atr.', validation_summary='none; source constant')
    touch_band_atr: float = config_field(0.18, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.touch_band_atr.', validation_summary='none; source constant')

class StrategiesAutoScalpLookbacksConfig(FrozenConfigModel):
    m15_bars: int = config_field(64, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.lookbacks.m15_bars.', validation_summary='none; source constant')
    m1_bars: int = config_field(120, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.lookbacks.m1_bars.', validation_summary='none; source constant')
    m5_bars: int = config_field(96, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.lookbacks.m5_bars.', validation_summary='none; source constant')

class StrategiesAutoScalpConfig(FrozenConfigModel):
    box: StrategiesAutoScalpBoxConfig = Field(default_factory=StrategiesAutoScalpBoxConfig)
    execution_timeframe: str = config_field('M1', canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.ENUM, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.execution_timeframe.', validation_summary='none; source constant')
    lookbacks: StrategiesAutoScalpLookbacksConfig = Field(default_factory=StrategiesAutoScalpLookbacksConfig)

class StrategiesCounterTrendConfig(FrozenConfigModel):
    allow_counter_trend: bool = config_field(True, canonical_env='ALLOW_COUNTER_TREND', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    extreme_pd: float = config_field(0.25, canonical_env='COUNTER_EXTREME_PD', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.25),), validation_summary='Pydantic required/type coercion only')
    level_min_touches: int = config_field(3, canonical_env='COUNTER_LEVEL_MIN_TOUCHES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),), validation_summary='Pydantic required/type coercion only')
    min_zone_score: float = config_field(10.0, canonical_env='COUNTER_MIN_ZONE_SCORE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SCORE, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 10.0),), validation_summary='Pydantic required/type coercion only')

class StrategiesSelectionConfig(FrozenConfigModel):
    box_breakout_enabled: bool = config_field(False, canonical_env='AUTO_TRADE_BOX_BREAKOUT_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    momentum_ride_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_MOMENTUM_RIDE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    retest_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_RETEST_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    snap_back_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_SNAP_BACK_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesBreakoutConfig(FrozenConfigModel):
    break_retest_enabled: bool = config_field(False, canonical_env='AUTO_TRADE_BREAK_RETEST_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    breakout_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_BREAKOUT_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')

class StrategiesReactionDemandConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_DEMAND_REACTION_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesReactionKeyLevelConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_KEY_LEVEL_REACTION_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    # Quality gates (off globally; enable per-instrument via overrides). Dig
    # 2026-08-25: GBPJPY Key Level was 0/4 and −118 pips — mostly Asia/
    # outside + ambiguous / counter-bias prints. Keep the detector live;
    # raise the bar instead of disabling the family.
    require_explicit_role: bool = config_field(False, canonical_env='AUTO_TRADE_KEY_LEVEL_REQUIRE_EXPLICIT_ROLE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Skip ambiguous-role Key Level (explicit support/resistance kind only).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    require_killzone: bool = config_field(False, canonical_env='AUTO_TRADE_KEY_LEVEL_REQUIRE_KILLZONE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Require killzone for Key Level even when global reaction_require_killzone is off.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    require_htf_alignment: bool = config_field(False, canonical_env='AUTO_TRADE_KEY_LEVEL_REQUIRE_HTF_ALIGNMENT', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Require Key Level direction to match HTF bias.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    min_grade: str = config_field('B', canonical_env='AUTO_TRADE_KEY_LEVEL_MIN_GRADE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Minimum ZoneWatch grade for Key Level Reaction (A or B).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'B'),), allowed_values=('A', 'B'), validation_summary='Pydantic type coercion + field validator', pattern='^[AB]$')

    @field_validator('min_grade', mode='before')
    @classmethod
    def normalize_min_grade(cls, value):
        return value.strip().upper() if isinstance(value, str) else value

class StrategiesReactionLiquidityReversalConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_LIQUIDITY_REVERSAL_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')

class StrategiesReactionSessionLevelConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_SESSION_LEVEL_REACTION_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesReactionSupplyConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_SUPPLY_REACTION_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesReactionTrendlineConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TRENDLINE_REACTION_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesReactionConfig(FrozenConfigModel):
    demand: StrategiesReactionDemandConfig = Field(default_factory=StrategiesReactionDemandConfig)
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_REACTION_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    key_level: StrategiesReactionKeyLevelConfig = Field(default_factory=StrategiesReactionKeyLevelConfig)
    liquidity_reversal: StrategiesReactionLiquidityReversalConfig = Field(default_factory=StrategiesReactionLiquidityReversalConfig)
    scale_enabled: bool = config_field(False, canonical_env='AUTO_TRADE_REACTION_SCALE_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    session_level: StrategiesReactionSessionLevelConfig = Field(default_factory=StrategiesReactionSessionLevelConfig)
    supply: StrategiesReactionSupplyConfig = Field(default_factory=StrategiesReactionSupplyConfig)
    trendline: StrategiesReactionTrendlineConfig = Field(default_factory=StrategiesReactionTrendlineConfig)

class StrategiesScalpConfig(FrozenConfigModel):
    fade_scalp_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_FADE_SCALP_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    scalp_barrier_fallback_enabled: bool = config_field(True, canonical_env='SCALP_BARRIER_FALLBACK_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    scalp_barrier_fallback_min_confirmations: int = config_field(1, canonical_env='SCALP_BARRIER_FALLBACK_MIN_CONFIRMATIONS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1),), validation_summary='Pydantic required/type coercion only')
    scalp_post_impulse_range_enabled: bool = config_field(True, canonical_env='SCALP_POST_IMPULSE_RANGE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    scalp_range_provisional_enabled: bool = config_field(True, canonical_env='SCALP_RANGE_PROVISIONAL_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesMappedZoneConfig(FrozenConfigModel):
    counter_bias_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_MAP_COUNTER_BIAS_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_MAPPED_ZONE_ENABLED', deprecated_env_aliases=('AUTO_TRADE_MARKET_MAP_STRATEGY_ENABLED',), owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.Bool + AutoTradeOptions.Validate', evidence_notes=('Direct demo_eval resolves true while root Compose demo_eval injects false.',))

class StrategiesMatchingConfig(FrozenConfigModel):
    multiple_matches_enabled: bool = config_field(False, canonical_env='AUTO_TRADE_MULTI_MATCH_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.EXECUTION_SAFETY, shared_with_ctrader=True, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    track_all_structural_matches: bool = config_field(False, canonical_env='AUTO_TRADE_TRACK_ALL_STRUCTURAL_MATCHES', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.EXECUTION_SAFETY, shared_with_ctrader=True, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')

class StrategiesRangeReversionRangeEdgeConfig(FrozenConfigModel):
    allow_rejection_only: bool = config_field(True, canonical_env='RANGE_SCALP_ALLOW_REJECTION_ONLY', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    break_closes: int = config_field(2, canonical_env='RANGE_SCALP_BREAK_CLOSES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.VERSION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    cluster_atr: float = config_field(0.25, canonical_env='RANGE_SCALP_CLUSTER_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.25),), validation_summary='Pydantic required/type coercion only')
    cluster_min_abs: float = config_field(0.0, canonical_env='RANGE_SCALP_CLUSTER_MIN_ABS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (price).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.0),), validation_summary='Pydantic required/type coercion only')
    enabled: bool = config_field(True, canonical_env='RANGE_SCALP_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    entry_tol_atr: float = config_field(0.25, canonical_env='RANGE_SCALP_ENTRY_TOL_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.25),), validation_summary='Pydantic required/type coercion only')
    lookback: int = config_field(48, canonical_env='RANGE_SCALP_LOOKBACK', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 48),), validation_summary='Pydantic required/type coercion only')
    max_edge_width_atr: float = config_field(0.75, canonical_env='RANGE_SCALP_MAX_EDGE_WIDTH_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.75),), validation_summary='Pydantic required/type coercion only')
    max_width_atr: float = config_field(6.0, canonical_env='RANGE_SCALP_MAX_WIDTH_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 6.0),), validation_summary='Pydantic required/type coercion only')
    min_inside_closes: int = config_field(3, canonical_env='RANGE_SCALP_MIN_INSIDE_CLOSES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.VERSION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),), validation_summary='Pydantic required/type coercion only')
    min_room_atr: float = config_field(0.75, canonical_env='RANGE_SCALP_MIN_ROOM_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.75),), validation_summary='Pydantic required/type coercion only')
    min_touches: int = config_field(2, canonical_env='RANGE_SCALP_MIN_TOUCHES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.VERSION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    min_wick_frac: float = config_field(0.25, canonical_env='RANGE_SCALP_MIN_WICK_FRAC', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.25),), validation_summary='Pydantic required/type coercion only')
    min_wick_rejections: int = config_field(1, canonical_env='RANGE_SCALP_MIN_WICK_REJECTIONS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.VERSION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1),), validation_summary='Pydantic required/type coercion only')
    min_width_atr: float = config_field(1.0, canonical_env='RANGE_SCALP_MIN_WIDTH_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.0),), validation_summary='Pydantic required/type coercion only')

class StrategiesRangeReversionConfig(FrozenConfigModel):
    box_scale_out_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_RANGE_BOX_SCALE_OUT_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_RANGE_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    flip_enabled: bool = config_field(False, canonical_env='AUTO_TRADE_RANGE_FLIP_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    range_edge: StrategiesRangeReversionRangeEdgeConfig = Field(default_factory=StrategiesRangeReversionRangeEdgeConfig)
    two_sided_enabled: bool = config_field(False, canonical_env='AUTO_TRADE_RANGE_TWO_SIDED_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')

class StrategiesTrendConfig(FrozenConfigModel):
    allow_chase: bool = config_field(False, canonical_env='TREND_ALLOW_CHASE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    atr_baseline_bars: int = config_field(48, canonical_env='TREND_ATR_BASELINE_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 48),), validation_summary='Pydantic required/type coercion only')
    atr_expansion_multiplier: float = config_field(1.15, canonical_env='TREND_ATR_EXPANSION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MULTIPLIER, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (multiplier).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.15),), validation_summary='Pydantic required/type coercion only')
    breakout_accept_bars: int = config_field(2, canonical_env='TREND_BREAKOUT_ACCEPT_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    breakout_max_age_bars: int = config_field(5, canonical_env='TREND_BREAKOUT_MAX_AGE_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5),), validation_summary='Pydantic required/type coercion only')
    breakout_min_room_pips: int = config_field(35, canonical_env='TREND_BREAKOUT_MIN_ROOM_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (pips).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 35),), validation_summary='Pydantic required/type coercion only')
    enabled: bool = config_field(False, canonical_env='AUTO_TRADE_TREND_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    level_buffer_atr: float = config_field(1.0, canonical_env='TREND_LEVEL_BUFFER_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.0),), validation_summary='Pydantic required/type coercion only')
    min_height_atr: float = config_field(3.0, canonical_env='TREND_MIN_HEIGHT_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3.0),), validation_summary='Pydantic required/type coercion only')
    minimum_bos: int = config_field(2, canonical_env='TREND_MIN_BOS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    pullback_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TREND_PULLBACK_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesZoneDemandConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_DEMAND_ZONE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls value.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesZoneSupplyConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_SUPPLY_ZONE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls value.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesZoneFlipConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_FLIP_ZONE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable Flip Zone (broken key-level role flip) under the Zone family. Uses flip_zone geometry from analysis; independent of Demand/Supply Zone Reaction and Reaction-family toggles.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesZoneConfig(FrozenConfigModel):
    demand: StrategiesZoneDemandConfig = Field(default_factory=StrategiesZoneDemandConfig)
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_ZONE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Master enable for independent Zone (supply/demand/flip) strategies.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    flip: StrategiesZoneFlipConfig = Field(default_factory=StrategiesZoneFlipConfig)
    supply: StrategiesZoneSupplyConfig = Field(default_factory=StrategiesZoneSupplyConfig)

class StrategiesTechniqueSdConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TECHNIQUE_SD_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable Supply Demand technique publisher.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesTechniqueObConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TECHNIQUE_OB_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable Order Block technique publisher.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesTechniqueFvgConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TECHNIQUE_FVG_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable FVG technique publisher.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    max_atr: float = config_field(2.0, canonical_env='AUTO_TRADE_TECHNIQUE_FVG_MAX_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Maximum FVG width in ATR.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2.0),), validation_summary='Pydantic required/type coercion only')
    entry_max_width_price: float = config_field(5.0, canonical_env='AUTO_TRADE_TECHNIQUE_FVG_ENTRY_MAX_WIDTH_PRICE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Proximal entry-band width for FVG/iFVG/imbalance zones (price). Full gap kept as structural bounds; every strategy clips tradeable entry to this width.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5.0),), validation_summary='Pydantic required/type coercion only', gt=0)

class StrategiesTechniqueIfvgConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TECHNIQUE_IFVG_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable iFVG technique publisher.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesTechniqueCrtConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TECHNIQUE_CRT_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable CRT technique publisher.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    min_atr: float = config_field(1.5, canonical_env='AUTO_TRADE_TECHNIQUE_CRT_MIN_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Minimum H1 impulse range in ATR for CRT.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.5),), validation_summary='Pydantic required/type coercion only')
    reclaim_bars: int = config_field(6, canonical_env='AUTO_TRADE_TECHNIQUE_CRT_RECLAIM_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Execution TF bars allowed for CRT reclaim.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 6),), validation_summary='Pydantic required/type coercion only')
    entry_max_width_price: float = config_field(5.0, canonical_env='AUTO_TRADE_TECHNIQUE_CRT_ENTRY_MAX_WIDTH_PRICE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Proximal reclaim entry-band width for CRT (price). Full H1 candle kept as structural bounds; tradeable entry clips to this width (same default contract as FVG).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5.0),), validation_summary='Pydantic required/type coercion only', gt=0)
    h1_lookback_bars: int = config_field(3, canonical_env='AUTO_TRADE_TECHNIQUE_CRT_H1_LOOKBACK_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Closed H1 candles scanned for CRT impulse (forming bar excluded).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),), validation_summary='Pydantic required/type coercion only', ge=1)

class StrategiesTechniqueConfluenceConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_CONFLUENCE_ZONE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable Confluence Zone publisher when 2+ techniques overlap.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesTechniqueZoneReactionFallbackConfig(FrozenConfigModel):
    enabled: bool = config_field(False, canonical_env='AUTO_TRADE_ZONE_REACTION_FALLBACK_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Zone Reaction fallback when technique publishers are active.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')

class StrategiesTechniqueConfig(FrozenConfigModel):
    sd: StrategiesTechniqueSdConfig = Field(default_factory=StrategiesTechniqueSdConfig)
    ob: StrategiesTechniqueObConfig = Field(default_factory=StrategiesTechniqueObConfig)
    fvg: StrategiesTechniqueFvgConfig = Field(default_factory=StrategiesTechniqueFvgConfig)
    ifvg: StrategiesTechniqueIfvgConfig = Field(default_factory=StrategiesTechniqueIfvgConfig)
    crt: StrategiesTechniqueCrtConfig = Field(default_factory=StrategiesTechniqueCrtConfig)
    confluence: StrategiesTechniqueConfluenceConfig = Field(default_factory=StrategiesTechniqueConfluenceConfig)
    zone_reaction_fallback: StrategiesTechniqueZoneReactionFallbackConfig = Field(default_factory=StrategiesTechniqueZoneReactionFallbackConfig)

class StrategiesHighFrequencyScalpArchetypesConfig(FrozenConfigModel):
    breakout_retest_enabled: bool = config_field(True, canonical_env='HFS_BREAKOUT_RETEST_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable micro breakout-retest HFS archetype.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    impulse_pullback_enabled: bool = config_field(True, canonical_env='HFS_IMPULSE_PULLBACK_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable impulse pullback continuation HFS archetype (on by default for L1 continuation).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    # Live 2026-08-12: Momentum Chase 12 trades / −166 pips (avg −13.8). Stay
    # off by default; ignition thresholds tightened when explicitly enabled.
    momentum_chase_enabled: bool = config_field(False, canonical_env='HFS_MOMENTUM_CHASE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable momentum ignition chase HFS archetype (off by default after quality dig).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    range_sweep_enabled: bool = config_field(True, canonical_env='HFS_RANGE_SWEEP_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable micro range sweep reversal HFS archetype.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesHighFrequencyScalpContextConfig(FrozenConfigModel):
    current_context_ttl_seconds: int = config_field(3600, canonical_env='HFS_CURRENT_CONTEXT_TTL_SECONDS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SECONDS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='TTL for current immutable M5 scalp context.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3600),), validation_summary='Pydantic required/type coercion only', ge=60)
    historic_context_ttl_seconds: int = config_field(86400, canonical_env='HFS_HISTORIC_CONTEXT_TTL_SECONDS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SECONDS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='TTL for historic scalp context snapshots.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 86400),), validation_summary='Pydantic required/type coercion only', ge=3600)
    m1_lookback_bars: int = config_field(60, canonical_env='HFS_M1_LOOKBACK_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Bounded M1 lookback for microstructure.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 60),), validation_summary='Pydantic required/type coercion only', ge=20)
    maximum_m5_age_seconds: int = config_field(420, canonical_env='HFS_MAXIMUM_M5_AGE_SECONDS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SECONDS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Fail closed when pinned M5 context is older than this.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 420),), validation_summary='Pydantic required/type coercion only', ge=60)

class StrategiesHighFrequencyScalpLocationConfig(FrozenConfigModel):
    # Live 2026-08-12 taxonomy: Impulse Pullback bled mid-range; tighten toward value.
    pullback_buy_maximum_position: float = config_field(0.60, canonical_env='HFS_PULLBACK_BUY_MAX_POSITION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.EXECUTION_SAFETY, description='Max dealing-range position for HFS pullback BUY.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.60),), validation_summary='Pydantic required/type coercion only', ge=0, le=1)
    pullback_sell_minimum_position: float = config_field(0.40, canonical_env='HFS_PULLBACK_SELL_MIN_POSITION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.EXECUTION_SAFETY, description='Min dealing-range position for HFS pullback SELL.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.40),), validation_summary='Pydantic required/type coercion only', ge=0, le=1)
    range_buy_maximum_position: float = config_field(0.35, canonical_env='HFS_RANGE_BUY_MAX_POSITION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.EXECUTION_SAFETY, description='Max dealing-range position for HFS range-sweep BUY.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.35),), validation_summary='Pydantic required/type coercion only', ge=0, le=1)
    range_sell_minimum_position: float = config_field(0.65, canonical_env='HFS_RANGE_SELL_MIN_POSITION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.EXECUTION_SAFETY, description='Min dealing-range position for HFS range-sweep SELL.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.65),), validation_summary='Pydantic required/type coercion only', ge=0, le=1)

class StrategiesHighFrequencyScalpActivationConfig(FrozenConfigModel):
    # Align with execution.entry.maximum_chase_distance_pips (was 100 → late chase bleed).
    maximum_chase_pips: float = config_field(40.0, canonical_env='HFS_MAXIMUM_CHASE_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.EXECUTION_SAFETY, description='Miss opportunity beyond this chase distance.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 40.0),), validation_summary='Pydantic required/type coercion only', ge=0)
    rearm_distance_atr: float = config_field(0.25, canonical_env='HFS_REARM_DISTANCE_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Minimum distance to rearm an episode.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.25),), validation_summary='Pydantic required/type coercion only', ge=0)
    trigger_maximum_age_bars: int = config_field(2, canonical_env='HFS_TRIGGER_MAXIMUM_AGE_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.EXECUTION_SAFETY, description='Max closed M1 bars since trigger.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only', ge=1)

class StrategiesHighFrequencyScalpTargetConfig(FrozenConfigModel):
    minimum_net_target_pips: float = config_field(15.0, canonical_env='HFS_MINIMUM_NET_TARGET_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.EXECUTION_SAFETY, description='Minimum net target after spread/slippage.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 15.0),), validation_summary='Pydantic required/type coercion only', ge=1)
    preferred_ladder_pips: str = config_field('20,25,30', canonical_env='HFS_PREFERRED_LADDER_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.STRING, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Comma-separated preferred scalp targets in pips.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, '20,25,30'),), validation_summary='Pydantic required/type coercion only')

class StrategiesHighFrequencyScalpStopConfig(FrozenConfigModel):
    buffer_atr: float = config_field(0.1, canonical_env='HFS_STOP_BUFFER_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.EXECUTION_SAFETY, description='ATR buffer beyond structural stop.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.1),), validation_summary='Pydantic required/type coercion only', ge=0)
    # Dig 2026-08-25: TradePlan ignored this cap (reaction 40–60). Owner raised
    # max to 30 so Range Sweep structure room can plan without clipping too hard.
    maximum_pips: float = config_field(30.0, canonical_env='HFS_STOP_MAXIMUM_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.EXECUTION_SAFETY, description='Maximum scalp stop size.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 30.0),), validation_summary='Pydantic required/type coercion only', ge=1)
    minimum_pips: float = config_field(12.0, canonical_env='HFS_STOP_MINIMUM_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.EXECUTION_SAFETY, description='Minimum scalp stop size.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 12.0),), validation_summary='Pydantic required/type coercion only', ge=1)

class StrategiesHighFrequencyScalpPolicyConfig(FrozenConfigModel):
    maximum_active_opportunities: int = config_field(10, canonical_env='HFS_MAXIMUM_ACTIVE_OPPORTUNITIES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Cap on concurrently active scalp opportunities.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 10),), validation_summary='Pydantic required/type coercion only', ge=1)
    maximum_opportunities_per_cycle: int = config_field(3, canonical_env='HFS_MAXIMUM_OPPORTUNITIES_PER_CYCLE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Ranked opportunities retained per M1 cycle.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),), validation_summary='Pydantic required/type coercion only', ge=1)
    maximum_spread_pips: float = config_field(5.0, canonical_env='HFS_MAXIMUM_SPREAD_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.EXECUTION_SAFETY, description='Hard block when spread exceeds this.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5.0),), validation_summary='Pydantic required/type coercion only', ge=0)
    minimum_reward_risk: float = config_field(1.1, canonical_env='HFS_MINIMUM_REWARD_RISK', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MULTIPLIER, risk=RiskClassification.EXECUTION_SAFETY, description='Minimum net reward/risk for HFS entries.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.1),), validation_summary='Pydantic required/type coercion only', ge=0)

class StrategiesHighFrequencyScalpRiskConfig(FrozenConfigModel):
    cooldown_after_loss_minutes: int = config_field(5, canonical_env='HFS_COOLDOWN_AFTER_LOSS_MINUTES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MINUTES, risk=RiskClassification.EXECUTION_SAFETY, description='Cooldownoldown after consecutive loss streak.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5),), validation_summary='Pydantic required/type coercion only', ge=0)
    daily_loss_limit_r: float = config_field(3.0, canonical_env='HFS_DAILY_LOSS_LIMIT_R', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MULTIPLIER, risk=RiskClassification.EXECUTION_SAFETY, description='Daily realized R loss limit.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3.0),), validation_summary='Pydantic required/type coercion only', ge=0)
    maximum_concurrent_positions: int = config_field(1, canonical_env='HFS_MAXIMUM_CONCURRENT_POSITIONS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.EXECUTION_SAFETY, description='One XAU scalp position at a time initially.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1),), validation_summary='Pydantic required/type coercion only', ge=1)
    maximum_consecutive_losses: int = config_field(3, canonical_env='HFS_MAXIMUM_CONSECUTIVE_LOSSES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.EXECUTION_SAFETY, description='Loss streak before cooldown.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),), validation_summary='Pydantic required/type coercion only', ge=1)
    maximum_daily_trades: int = config_field(30, canonical_env='HFS_MAXIMUM_DAILY_TRADES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.EXECUTION_SAFETY, description='Hard daily trade cap for HFS.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 30),), validation_summary='Pydantic required/type coercion only', ge=1)
    maximum_session_trades: int = config_field(12, canonical_env='HFS_MAXIMUM_SESSION_TRADES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.EXECUTION_SAFETY, description='Hard session trade cap for HFS.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 12),), validation_summary='Pydantic required/type coercion only', ge=1)
    mode: str = config_field('live', canonical_env='HFS_RISK_MODE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.EXECUTION_SAFETY, description='HFS risk accounting mode.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'live'),), allowed_values=('shadow', 'paper', 'live'), validation_summary='Pydantic type coercion + field validator', pattern='^(shadow|paper|live)$')
    risk_fraction_per_trade: float = config_field(0.1, canonical_env='HFS_RISK_FRACTION_PER_TRADE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.EXECUTION_SAFETY, description='Constant risk fraction — never martingale.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.1),), validation_summary='Pydantic required/type coercion only', ge=0, le=1)
    session_loss_limit_r: float = config_field(2.0, canonical_env='HFS_SESSION_LOSS_LIMIT_R', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MULTIPLIER, risk=RiskClassification.EXECUTION_SAFETY, description='Session realized R loss limit.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2.0),), validation_summary='Pydantic required/type coercion only', ge=0)

class StrategiesHighFrequencyScalpConfig(FrozenConfigModel):
    activation: StrategiesHighFrequencyScalpActivationConfig = Field(default_factory=StrategiesHighFrequencyScalpActivationConfig)
    archetypes: StrategiesHighFrequencyScalpArchetypesConfig = Field(default_factory=StrategiesHighFrequencyScalpArchetypesConfig)
    context: StrategiesHighFrequencyScalpContextConfig = Field(default_factory=StrategiesHighFrequencyScalpContextConfig)
    location: StrategiesHighFrequencyScalpLocationConfig = Field(default_factory=StrategiesHighFrequencyScalpLocationConfig)
    mode: str = config_field('live', canonical_env='HFS_MODE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.EXECUTION_SAFETY, description='HFS runtime mode: off, shadow, paper, or live.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'live'),), allowed_values=('off', 'shadow', 'paper', 'live'), validation_summary='Pydantic type coercion + field validator', pattern='^(off|shadow|paper|live)$')
    policy: StrategiesHighFrequencyScalpPolicyConfig = Field(default_factory=StrategiesHighFrequencyScalpPolicyConfig)
    risk: StrategiesHighFrequencyScalpRiskConfig = Field(default_factory=StrategiesHighFrequencyScalpRiskConfig)
    stop: StrategiesHighFrequencyScalpStopConfig = Field(default_factory=StrategiesHighFrequencyScalpStopConfig)
    target: StrategiesHighFrequencyScalpTargetConfig = Field(default_factory=StrategiesHighFrequencyScalpTargetConfig)

class StrategiesConfig(FrozenConfigModel):
    auto_scalp: StrategiesAutoScalpConfig = Field(default_factory=StrategiesAutoScalpConfig)
    breakout: StrategiesBreakoutConfig = Field(default_factory=StrategiesBreakoutConfig)
    counter_trend: StrategiesCounterTrendConfig = Field(default_factory=StrategiesCounterTrendConfig)
    high_frequency_scalp: StrategiesHighFrequencyScalpConfig = Field(default_factory=StrategiesHighFrequencyScalpConfig)
    mapped_zone: StrategiesMappedZoneConfig = Field(default_factory=StrategiesMappedZoneConfig)
    matching: StrategiesMatchingConfig = Field(default_factory=StrategiesMatchingConfig)
    range_reversion: StrategiesRangeReversionConfig = Field(default_factory=StrategiesRangeReversionConfig)
    reaction: StrategiesReactionConfig = Field(default_factory=StrategiesReactionConfig)
    scalp: StrategiesScalpConfig = Field(default_factory=StrategiesScalpConfig)
    selection: StrategiesSelectionConfig = Field(default_factory=StrategiesSelectionConfig)
    trend: StrategiesTrendConfig = Field(default_factory=StrategiesTrendConfig)
    technique: StrategiesTechniqueConfig = Field(default_factory=StrategiesTechniqueConfig)
    zone: StrategiesZoneConfig = Field(default_factory=StrategiesZoneConfig)
